### ISSUE TITLE
 The image id does not exist (InvalidAMIID.NotFound)

### ISSUE THREAD

**Issue by 3h4x** [cloudfoundry-incubator/lattice#100]
Terraform can't deploy because AMI's are outdated here https://github.com/3h4x/lattice/blob/master/terraform/aws/variables.tf

**Comment by davidwadden** [comment]
@3h4x we attempted to reproduce the issue reported, and it looks as though the AMIs we have defined are still working.  i did see a new version (20150417) of the 14.04 ubuntu were published, but i suspect the error you're getting is from a mismatch between the AMI it's attempting to provision and the region specified.  

Can you tell us which region you're attempting to deploy to?

Also, we'd be happy to consider the PR, but we need a signed CLA on file in order to merge it.

**Comment by 3h4x** [comment]
yop,
youre right. i've acted too hasty with my PR because I've used outdated repo https://github.com/cf-platform-eng/lattice-terraform and I thought the same mistake is here...

Can you tell me where to send CLA? 
I reckon new AMI's still can be merged, so may openSSL bugs out there ;)

**Comment by menicosia** [comment]
Hey @3h4x!

Thanks for submitting this pull request!

All pull request authors must have a Contributor License Agreement (CLA) on-file with us. Please sign the appropriate CLA (individual or corporate).

When sending signed CLA please provide your github username in case of individual CLA or the list of github usernames that can make pull requests on behalf of your organization.

**Comment by menicosia** [comment]
Hey @3h4x!

> Can you tell me where to send CLA? 

Here's what the bot blats for every pull request, including your PR #101:

----
All pull request authors must have a Contributor License Agreement (CLA) on-file with us. Please sign the appropriate CLA ([individual](http://cloudfoundry.org/pdfs/CFF_Individual_CLA.pdf) or [corporate](http://cloudfoundry.org/pdfs/CFF_Corporate_CLA.pdf)).

When sending signed CLA please provide your github username in case of individual CLA or the list of github usernames that can make pull requests on behalf of your organization.

----
Inside the doc, it tells you to send electronic versions to: contributors@cloudfoundry.org.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by 3h4x** [comment]
@menicosia Thanks mate!
all clear now :)

**Comment by 3h4x** [comment]
@davidwadden 
yesterday I have signed CLA so if you are willing to merge this PR, then go ahead :)

**Comment by davidwadden** [comment]
@3h4x - we're okay with the PR, but this story has been prioritized out a week+ (see [tracker link](https://www.pivotaltracker.com/story/show/92753222) above) .. i want to keep the OSes on the cluster in sync between terraform and vagrant -- #53 is a similar PR for the vagrant configuration.

**Comment by 3h4x** [comment]
Well it's perfectly reasonable.

**Comment by menicosia** [comment]
Hi there!

I've validated that the AMI is now Ubuntu 14.04.2 per PR #101, so I am closing this issue.

As always, please feel free to re-open if you think something would be lost by doing so. Thanks!

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by 3h4x** [comment]
thanks @davidwadden and @menicosia
btw: PR 101 sounds pr0 :D

**Comment by menicosia** [comment]
Hi @3h4x,

We've released Version 0.2.5 of Lattice that uses these new AMIs. Thanks for the accompanying PR!

https://github.com/cloudfoundry-incubator/lattice/releases/tag/v0.2.5

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
