### ISSUE TITLE
DNS resolver

### ISSUE THREAD

**Issue by aljacinto** [cloudfoundry-incubator/lattice#127]
I followed the dnsmasq instruction and everything is working (per instruction) but when using ltc, it's not resolving to proper host.  I can ping and do "host lattice.dev 127.0.0.1" but the ltc target comes up with no host error.
'''
Error verifying target: Get http://receptor.lattice.dev/v1/desired_lrps: dial tcp: lookup receptor.lattice.dev: no such host
'''

environment is mac, running with proxy

thanks in advance

**Comment by davidwadden** [comment]
You're not to first to find this one.   I think this sounds a bit like the one @menicosia reported in [**#93633072**](https://www.pivotaltracker.com/story/show/93633072)

It's like dnsmasq is totally fine on its own, but the system resolver isn't routing `*.dev` resolutions to **dnsmasq** properly?  Does that agree with the behavior you're seeing?

We didn't have much luck triaging it once before.  But found this looking around:

http://arstechnica.com/apple/2015/01/why-dns-in-os-x-10-10-is-broken-and-what-you-can-do-to-fix-it/

Out of curiosity, what version of OSX are you running?

David

**Comment by aljacinto** [comment]
Hi David,

Mac version is 10.10.3

The behavior you described is what I am seeing.  In addition, other tools like ping seems to go through dnsmasq, just can't get ltc CLI to do the same.
```
➜  ping lattice.dev
PING lattice.dev (192.168.11.11): 56 data bytes
```
host command without the [server] behaves the same as ltc CLI, it doesn't go to 127.0.0.1 first.
```
➜  host lattice.dev
lattice.dev mail is handled by 9 *************************.com.
lattice.dev mail is handled by 9 *************************.com.
lattice.dev mail is handled by 5 *************************.com.
```

with the server works because it knows where to check.  Which tells me it's not respecting the /etc/resolver/lattice.dev file which tells it for anything lattice.dev hit the nameserver inside the file first

```
➜  host lattice.dev 127.0.0.1
Using domain server:
Name: 127.0.0.1
Address: 127.0.0.1#53
Aliases:

lattice.dev has address 192.168.11.11
```

I'll checkout the link, thanks.  Of course, when I change my DNS to 127.0.0.1, it'll work but no more internet :)

**Comment by davidwadden** [comment]
Okay, yes this matches the same behavior our PM has seen.  Sorry for not getting back sooner, we've been focused on trying to get some new functionality through and it's summer =)  It's a bit mind-boggling since all the tools we use to diagnose + triage the issue all report everything is gravy --  it's just `ltc` that seems to use the wrong resolver.

Anyways, we came across this [article](https://support.apple.com/en-us/HT202516) (adding to our docs with [**#96956038**](https://www.pivotaltracker.com/story/show/96956038)) and are working on adding it our troubleshooting docs.  It's my guess currently that OS X 10.10 (w/ discoveryd) is getting poisoned somehow by `xip.io`.   Mind giving it a whirl and letting us know if it helps at all?

**Comment by aljacinto** [comment]
No luck :)  I even unload and load dnsmasq just to make sure.  It's weird because even curl work.  I can see it returning something.

```
➜  cli git:(master) ✗ ./ltc target lattice.dev
Error verifying target: Get http://receptor.lattice.dev/v1/desired_lrps: dial tcp: lookup receptor.lattice.dev: no such host
➜  cli git:(master) ✗ curl http://receptor.lattice.dev/v1/desired_lrps
[]%
```

**Comment by aljacinto** [comment]
David, finally got it to work - I tried the configuration here - http://blog.philippklaus.de/2012/02/install-dnsmasq-locally-on-mac-os-x-via-homebrew/

Thanks,
Alex

**Comment by davidwadden** [comment]
I added that link to our site at http://lattice.cf/docs/dnsmasq-readme/#installation.  

Thanks for letting us know
