### ISSUE TITLE
Error verifying target dial tcp: i/o timeout

### ISSUE THREAD

**Issue by dwatrous** [cloudfoundry-incubator/lattice#128]
I've used terraform to deploy a lattice cluster to digitalocean. Everything appears to complete as expected and it prints out the target, username and password. However, when I try to target I get this:

vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ltc target 192.241.195.49.xip.io
Error verifying target: Get http://receptor.192.241.195.49.xip.io/v1/desired_lrps: dial tcp: i/o timeout

If I SSH into the host at 192.241.195.49, I see that receptor is running. If I install the ltc client locally, I am able to target and login. Any idea why I can't access it from the host where I ran 'terraform apply'?

**Comment by dwatrous** [comment]
After digging around, I have found that this error only occurs on a vagrant created ubuntu server based on the official ubuntu trusty image:

vagrant init ubuntu/trusty64
vagrant up --provider virtualbox

I can ltc target from the brain box. I can also use vagrant to create a centos server and ltc target from there. I can also create a separate ubuntu server on digitalocean and ltc target from there.

I'm not sure what it is about the official ubuntu/trusty64 image that interferes with ltc target. I have even confirmed that I can load the receptor URL in w3m on the ubuntu/trusty64 server, but ltc target fails quickly every time.

**Comment by menicosia** [comment]
Hey @dwatrous,

Just to let you know, one of our people was able to replicate this. We're not sure what the root cause is yet, but we at least acknowledge that something hinky is indeed happening. Argh! We'll take a look.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by mgoelzer** [comment]
+1

It's happening for me too on vagrant (virtual box).  Problem is intermittent, and re-running the same command a second or two later will make it go away even though nothing has changed.  Example below.

----

liwi:lattice mgoelzer$ ltc visualize
Distribution
Error visualizing: Get http://receptor.192.168.11.11.xip.io/v1/cells: dial tcp: i/o timeout

liwi:lattice mgoelzer$ ltc visualize
Distribution
cell-01: •

**Comment by nielinjie** [comment]
+1 

ltc target fails quickly every time.
But I can access http://receptor.192.168.11.11.xip.io/v1/desired_lrps in my browser.

**Comment by menicosia** [comment]
Hey folks,

We're going to look into this. But before we dive in, can you all verify which version of the ltc command line you were using when you experienced these issues?

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.

**Comment by mgoelzer** [comment]
@menicosia 

$ ltc --version
ltc version v0.2.5

Let me know if there's any other info I can provide to help diagnose the issue.

**Comment by nielinjie** [comment]
@menicosia
ltc --version
ltc version v0.2.5

**Comment by davidwadden** [comment]
@dwatrous  i spent some time today with this, and was able to reproduce your situation

to clarify, this was with:
* terraform deployed cluster on digitalocean (and aws)
* ubuntu vagrant box (**NOT** the lattice/ubuntu-trusty-64 image, but an ubuntu/trusty64 image made with `vagrant init`)

to give some context of the `dial tcp: i/o timeout` error, it's a 5-second connect timeout on the `receptorClient`, defined with the following call path:

https://github.com/cloudfoundry-incubator/lattice/blob/master/ltc/cli_app_factory/cli_app_factory.go#L123
https://github.com/cloudfoundry-incubator/receptor/blob/master/client.go#L66-L67
https://github.com/cloudfoundry-incubator/cf_http/blob/master/cf_http.go#L27-L37

It looks like `ltc target`'s are taking about 5.6seconds from this image (so presumably hitting the , as opposed to baseline 0.1sec or so.

To the others @mgoelzer @nielinjie -- I'll try to gather some more details from you in the coming days, but the error message itself is very generic and lots of different underlying issues can manifest with that error message.  

```
root@vagrant-ubuntu-trusty-64:~# time curl -v http://user:pass@receptor.52.24.40.172.xip.io/v1/cells
* Hostname was NOT found in DNS cache
*   Trying 52.24.40.172...
* Connected to receptor.52.24.40.172.xip.io (52.24.40.172) port 80 (#0)
* Server auth using Basic with user 'user'
> GET /v1/cells HTTP/1.1
> Authorization: Basic dXNlcjpwYXNz
> User-Agent: curl/7.35.0
> Host: receptor.52.24.40.172.xip.io
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 191
< Content-Type: application/json
< Date: Mon, 15 Jun 2015 22:11:25 GMT
< X-Cf-Requestid: e8ab4e19-3d10-4350-6ed8-3cefeee33b1e
<
* Connection #0 to host receptor.52.24.40.172.xip.io left intact
[{"cell_id":"cell-0","zone":"z1","capacity":{"memory_mb":3764,"disk_mb":7924,"containers":256}},{"cell_id":"cell-1","zone":"z1","capacity":{"memory_mb":3764,"disk_mb":7924,"containers":256}}]
real	0m5.674s
user	0m0.000s
sys	0m0.007s
```

**Comment by damon-pivotal** [comment]
@dwatrous Are you running Vagrant on an OS X host? It looks like there might be an issue resolving against the DNS server running on the OS X host. We can reproduce this locally, but if we modify resolver.conf in Linux to point directly at 8.8.8.8 the delay goes away.

**Comment by dwatrous** [comment]
@damon-pivotal I'm running Vagrant + VirtualBox on Windows 8.1
I have been able to get around this by changing my from ubuntu/trusty64 to:
config.vm.box = "ubuntu/precise64"

@davidwadden I just changed back to trusty64 and deployed a new cluster to digitalocean. I was able to verify what you said. Is the timeout something I can change?

**Comment by davidwadden** [comment]
@dwatrous not easily.  we'd need to ask the diego team to make a change to let us provide a timeout when instantiating the `receptor.Client` .. did you try changing `/etc/resolv.conf` to use `8.8.8.8` instead?  (on **trusty64**)

i did try to reproduce using one of our lattice vagrant vms (built on top of ubuntu 14.04.2), and it had no issue

**Comment by dwatrous** [comment]
For now I can just use another image, like the old precise64 image.

**Comment by menicosia** [comment]
Hi @nielinjie,

We've been pretty frustrated by this cluster of issues. So far, we think that whatever's going on in your case is different than those who are having `dial tcp: i/o timeout` errors based on:
> ltc target fails quickly every time.

If you're still having this problem, can you please do two things:
1. Open a separate GitHub issue
2. Paste a typescript of what's going on in your session?

Sorry to be vague, this set of issues has been a real devil to make progress on.

**Comment by svrc-pivotal** [comment]
Same symptoms on AWS with ltc v0.2.6 server and client as @mgoelzer   - intermittent timeouts

worlock:example stuartcharlton$ ltc li
Error connecting to the receptor. Make sure your lattice target is set, and that lattice is up and running.
	Underlying error: Get http://user:pass@receptor.52.1.162.233.xip.io/v1/desired_lrps: dial tcp: i/o timeoutworlock:example stuartcharlton$ 
worlock:example stuartcharlton$ 
worlock:example stuartcharlton$ ltc li
Error listing apps: Get http://user:pass@receptor.52.1.162.233.xip.io/v1/desired_lrps: dial tcp: i/o timeoutworlock:example stuartcharlton$ ltc li
------------------------------= Apps =-------------------------------
No apps to display.

------------------------------= Tasks =------------------------------
No tasks to display.

**Comment by menicosia** [comment]
@svrc-pivotal, @dwatrous,

Just checking in on this ticket. I haven't seen any `dial tcp: i/o timeout` errors that weren't related to .xip.io slowness in quite some time. Usually re-retrying quickly resolves any issues.

Have you seen any problems with any of the v0.3 releases? (v0.3.2 will be released later today)

If this is no longer an issue, I'd like to close this out for now. We can always re-open or create new issues in the future.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by dwatrous** [comment]
@menicosia I haven't tested recently, so I can't say whether this is resolved, but I have already documented a workaround above, so for me this issue can be closed.

**Comment by svrc-pivotal** [comment]
I am still seeing this in v0.4.3 on AWS, for what it's worth.

**Comment by davidwadden** [comment]
@svrc-pivotal  can you try our latest [nightly bundle](https://lattice.s3.amazonaws.com/nightly/index.html) ?  
We made a change [[#103277682](https://www.pivotaltracker.com/story/show/103277682)] to [pre-warm the EBS volume](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-prewarm.html) that improves the responsiveness and performance of `ltc test` following a `terraform apply`.

If that doesn't seem to resolve the issues you're seeing, will you open a new issue?

@davidwadden

**Comment by svrc-pivotal** [comment]
Much better on the nightly.  I got a `dial tcp: i/o timeout` once after first launch, then not again despite running `ltc test` twice and launching various containers, tailing logs, etc.   Thanks!
