### ISSUE TITLE
openstack config is need to update for latest lattice changes

### ISSUE THREAD

**Issue by guanglinlv** [cloudfoundry-incubator/lattice#129]
hi,

https://github.com/cloudfoundry-incubator/lattice/blob/master/terraform/openstack/resources.tf

- `local-scripts` => `/scripts/local`
- `remote-scripts` => `/scripts/remote`
- `remote-scripts/install-lattice-coordinator` => `scripts/remote/install-brain` 
- `remote-scripts/install_from_tar` => `scripts/remote/install-from-tar` 
- `remote-scripts/install-lattice-cell` => `scripts/remote/install-cell`

**Comment by davidwadden** [comment]
@guanglinlv   we just put in a fix for the scripts.  it should land on master later on today

re: your question,  we haven't set up proxy configurations on our terraform deployments to date.  i could imagine something like the following maybe working:

1. update `source` directive in your `lattice.openstack.tf` [here](https://github.com/cloudfoundry-incubator/lattice/blob/master/terraform/openstack/example/lattice.openstack.tf#L2)
  - `source = "<relative_path_to_repo>/lattice/terraform/aws"`
1. run `terraform get -update` to point the modules to the local repo
1. make the following changes in `.terraform/modules/<SHA>/terraform/openstack/resources.tf`  (should be a symlink to the local repo)
  - insert ahead of [resources.tf:180](https://github.com/cloudfoundry-incubator/lattice/blob/master/terraform/openstack/resources.tf#L180) (and something similar on the brain section if needed):

```
    provisioner "remote-exec" {
      inline = [
          "echo http_proxy=http://proxy.url >> /etc/environment"
      ]
    }
```

**Comment by davidwadden** [comment]
I think we got it right.  This ought to be working in [v0.2.5](https://github.com/cloudfoundry-incubator/lattice/releases/tag/v0.2.5).

Open a new thread if you want to continue discussion on your side question regarding the proxy

Thanks!
David
