### ISSUE TITLE
run ltc from windows (cygwin)

### ISSUE THREAD

**Issue by cforce** [cloudfoundry-incubator/lattice#140]
I followed the installation sucessfully until .. but no matter what i can get ltc running at cygwin.

$ chmod +x ltc
$ ltc --version
-bash: /home/fwallwit/bin/ltc: cannot execute binary file: Exec format error

**Comment by menicosia** [comment]
Hi @cforce,

I'm sorry, Windows via cygwin isn't something that we've worked into Lattice. While the `ltc` command is written in Go, and therefore could theoretically work on Windows, the team hasn't prioritized that work yet.

Some people have attempted at getting Lattice to work (see issue #80 and #81) on Windows. We have written a story to support windows and are tracking it here: 85921380. You can follow that ticket in Tracker to monitor how we make progress against it. If you'd like to help in that effort, please check out the [contributing](https://github.com/cloudfoundry-incubator/lattice#contributing) section of our Readme.

We'll continue to iterate on making it easier for Windows folks in the meantime with documentation fixes and hopefully the occasional workaround.
