### ISSUE TITLE
ltc create lapp cloudfoundry/lattice-app => invalid field user

### ISSUE THREAD

**Issue by kdvolder** [cloudfoundry-incubator/lattice#141]
Today I pulled master and downloaded the latest ltc binary for linux. Now I can not create any more lattice-apps using ltc create. All I get is this error: 

     Error creating app: Invalid field: user, Invalid field: user

This worked yesterday deploying the exact same app(s) using the exact same command.

**Comment by menicosia** [comment]
Hey @kdvolder, OK we'll start looking into this soon.

**Comment by menicosia** [comment]
Hi @kdvolder,

You're running a risk when you pull from master that you're getting a newer version of Diego than Lattice supports. Diego is moving very quickly and has non-backward-compatible changes. If you aren't using one of the Lattice releases, you're likely to get a Lattice/Diego version mismatch - we have seen the same error you're experiencing in just such a situation.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by kdvolder** [comment]
> If you aren't using one of the Lattice releases, you're likely to get a Lattice/Diego version mismatch - we have seen the same error you're experiencing in just such a situation.

I don't really need to be on 'master' I think. But those are the only instructions I have. They come from here:  http://lattice.cf/docs/getting-started/

Do you have instructions for getting up and running with something more 'stable'?

**Comment by menicosia** [comment]
Hi @kdvolder,

Oh, thank you for pointing that out. I will find a way to update the instructions.

The only difference is that you would checkout a specific tag which correlates to a release: `git checkout v0.2.6`

Please let me know if that works better for you (and close this issue if it resolves the problem)!

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.

**Comment by kdvolder** [comment]
Thanks, v0.2.6 works. So this solves the issue for me for now.

However, let me point out one more potential 'hole' in the installation / distribution docs for lattice vagrant VM + ltc binary. 

I now have a easy way to get a specific version of lattice vagrant VM by checking out a specific tag.

Is there also a way to get a specific version of the 'ltc' command binary that is known to be compatible with that version?  I.e. maybe a variant of this command with a specifc version number?

     wget https://lattice.s3.amazonaws.com/releases/latest/linux-amd64/ltc -O $HOME/bin/ltc

Since it seems there is a version dependency between the 'ltc' command and the VM the instructions should make it clear how to get matching versions of both.

**Comment by menicosia** [comment]
You're right. I'll close this comment and update the story I wrote as a result of this issue: [98818296](https://www.pivotaltracker.com/story/show/98818296)

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.
