### ISSUE TITLE
lattice build issue (docker/docker and brtfs issue)

### ISSUE THREAD

**Issue by npramod** [cloudfoundry-incubator/lattice#148]
Trying to build lattice using instructions on https://github.com/cloudfoundry-incubator/lattice/blob/master/docs/development-readme.md. Getting errors at two places, a) with go get ./... in lattice repository
docker dependency errors.
package github.com/goamz/goamz/aws
imports github.com/vaughan0/go-ini
imports github.com/goamz/goamz/s3
imports github.com/gizak/termui
imports github.com/mattn/go-runewidth
imports github.com/nsf/termbox-go
imports github.com/codegangsta/cli
imports github.com/docker/docker/registry:
/Users/npramod/workspace/diego-release/src/github.com/docker/docker exists
but /Users/npramod/workspace/diego-release/src/github.com/docker/docker/.git
does not - stale checkout?
package github.com/goamz/goamz/aws
imports github.com/vaughan0/go-ini
imports github.com/goamz/goamz/s3
imports github.com/gizak/termui
imports github.com/mattn/go-runewidth
imports github.com/nsf/termbox-go
imports github.com/codegangsta/cli
imports github.com/docker/docker/image
imports github.com/docker/docker/image
imports github.com/docker/docker/image: cannot find package "
github.com/docker/docker/image" in any of:
/usr/local/go/src/github.com/docker/docker/image (from $GOROOT)
/Users/npramod/workspace/diego-release/src/github.com/docker/docker/image
(from $GOPATH)
package github.com/goamz/goamz/aws
imports github.com/vaughan0/go-ini
imports github.com/goamz/goamz/s3
imports github.com/gizak/termui
imports github.com/mattn/go-runewidth
imports github.com/nsf/termbox-go
imports github.com/codegangsta/cli
imports github.com/docker/docker/image
imports github.com/docker/docker/nat
imports github.com/docker/docker/nat
imports github.com/docker/docker/nat: cannot find package "
github.com/docker/docker/nat" in any of:
/usr/local/go/src/github.com/docker/docker/nat (from $GOROOT)
/Users/npramod/workspace/diego-release/src/github.com/docker/docker/nat
(from $GOPATH)
package github.com/goamz/goamz/aws
imports github.com/vaughan0/go-ini
imports github.com/goamz/goamz/s3
imports github.com/gizak/termui
imports github.com/mattn/go-runewidth
imports github.com/nsf/termbox-go
imports github.com/codegangsta/cli
imports github.com/docker/docker/image
imports github.com/docker/docker/nat
imports github.com/docker/docker/utils
imports github.com/docker/docker/utils
imports github.com/docker/docker/utils: cannot find package "
github.com/docker/docker/utils" in any of:
/usr/local/go/src/github.com/docker/docker/utils (from $GOROOT)
/Users/npramod/workspace/diego-release/src/github.com/docker/docker/utils
(from $GOPATH)

b) and if we ignore these go get errors from a), at last step of recompile_lattice throws the following error
recompile-lattice
Running command with /workspace/diego-release/src/
github.com/cloudfoundry-incubator/lattice/pipeline/01_compilation/compile_lattice_tar
/workspace/cf-release/src/loggregator /workspace
/workspace
setting up go env
copying diego release
copying cf release
copying lattice
staging common files
staging scripts
compiling cell
compiling garden linux
# github.com/docker/docker/daemon/graphdriver/btrfs
/root/workspace/diego-release/src/
github.com/cloudfoundry-incubator/garden-linux/Godeps/_workspace/src/github.com/docker/docker/daemon/graphdriver/btrfs/btrfs.go:8:25:
fatal error: btrfs/ioctl.h: No such file or directory
 #include <btrfs/ioctl.h>
                         ^
compilation terminated. 

Any thoughts on what the issue could be?
(we are trying some diego placement changes and getting lattice build to work is a blocker)

**Comment by dhilipkumars** [comment]
```
oot/workspace/diego-release/src/
github.com/cloudfoundry-incubator/garden-linux/Godeps/_workspace/src/github.com/docker/docker/daemon/graphdriver/btrfs/btrfs.go:8:25:
fatal error: btrfs/ioctl.h: No such file or directory
#include 
```

This appears to be related to garden-linux build failure.  Garden Linux uses the version of docker which needs btrfs so you need to [Install Btrfs tools if not present on your machine] (https://github.com/cloudfoundry-incubator/garden-linux) to get past it.

**Comment by npramod** [comment]
Installed btrfs-tools on the machine (ubuntu 14.04) the error changed to 
# github.com/docker/docker/daemon/graphdriver/btrfs
/root/workspace/diego-release/src/github.com/cloudfoundry-incubator/garden-linux/Godeps/_workspace/src/github.com/docker/docker/daemon/graphdriver/btrfs/version.go:6:27: fatal error: btrfs/version.h: No such file or directory
 #include <btrfs/version.h>
                           ^
compilation terminated.

We also updated the cloud foundry/lattice-pipeline image to include btrfs-tools --  same error 

Anyone with full lattice development environment working - can u pls share ur environment details.

**Comment by davidwadden** [comment]
We updated (https://github.com/cloudfoundry-incubator/lattice/commit/a49ebc14327e76e9a9548a04b12b681e736d87af) the [development-readme](https://github.com/cloudfoundry-incubator/lattice/blob/develop/docs/development-readme.md) a bit to hopefully reflect the two changes I think you need:

1.  checkout **0.1360.0** tag under diego-release (current compatible diego version for lattice on **master** is in [DIEGO_VERSION](https://github.com/cloudfoundry-incubator/lattice/blob/master/DIEGO_VERSION)

  a. `cd $GOPATH && ./scripts/update   ## assumes GOPATH is diego-release folder`

2. `rm -rf $GOPATH/src/github.com/docker/docker  ## same assumption`   

  a. `godep restore` 

If you get a chance, give our new instructions a try from the top, you might find this easier than trying to repair your current setup.  The "long form" instructions should be replaced very soon -- we are currently working on automating the open source developer environment setup with [[**#98769190**](https://www.pivotaltracker.com/story/show/98769190)], and this should be a much better experience than what it is today.

**Comment by npramod** [comment]
Thanks a ton for the quick update. I tried the updated instructions from scratch -- works like a charm!!!
Thx

**Comment by davidwadden** [comment]
cool!  i'll close this out then
