### ISSUE TITLE
Timed out waiting for the container to come up.

### ISSUE THREAD

**Issue by teodor-pripoae** [cloudfoundry-incubator/lattice#155]
Hi,

I'm getting this error while trying to run an xray container (hatofmonkeys/xray on dockerhub). This container runs fine in boot2docker but times out when running in lattice vagrant vm.

I ran it with -t `10m0s`, also with `20m0s`, it eventually times out. Running example lattice-app works. 

No progress is shown (something like downloaded 33mb/600mb), so I have no clue where it hangs. I guess it may be related with: https://github.com/cloudfoundry-incubator/garden-linux/pull/35

```
$ ltc create xray hatofmonkeys/xray -t "10m0s"
No port specified, using exposed ports from the image metadata.
	Exposed Ports: 8080
No working directory specified, using working directory from the image metadata...
Working directory is:
/app
Monitoring the app on port 8080...
No start command specified, using start command from the image metadata...
Start command is:
/bin/bash /app/cloudrocker-start-1c4352a23e52040ddb1857d7675fe3cc.sh /app npm start
Creating App: xray
.............07/30 07:32:01.90 [APP|0] Successfully created container
.07/30 07:32:02.08 [APP|0] Creating container
..07/30 07:32:04.99 [APP|0] Successfully created container
.07/30 07:32:05.13 [APP|0] Creating container
.......07/30 07:32:12.93 [APP|0] Successfully created container
..................................07/30 07:32:46.54 [APP|0] Creating container
...07/30 07:32:49.75 [APP|0] Successfully created container
......................................................................................07/30 07:34:16.57 [APP|0] Creating container
.........07/30 07:34:25.56 [APP|0] Successfully created container
.............................................................................................................................................07/30 07:36:46.64 [APP|0] Creating container
.......07/30 07:36:54.55 [APP|0] Successfully created container
.....................................................................................................................................................................................................................................................................07/30 07:41:16.74 [APP|0] Creating container
...07/30 07:41:19.59 [APP|0] Successfully created container
.............................
Timed out waiting for the container to come up.
This typically happens because docker layers can take time to download.
Lattice is still downloading your application in the background.
To view logs:
	ltc logs xray
To view status:
	ltc status xray

App will be reachable at
```

**Comment by teodor-pripoae** [comment]
Actually it seems the image was pulled successfully,it just timeouts when starting the container. Running it in docker works fine.

**Comment by teodor-pripoae** [comment]
Any help here ? I can see that the image is using user `vcap`, which I think lattice also uses internally. Running as root is not an option due to config paths using user `$HOME` variables.

**Comment by menicosia** [comment]
Hi @teodor-pripoae,

Sorry for the lag, I was out last week.

Which version of Lattice are you using, and are you sure you're using the same version `ltc` binary as the Lattice that you've deployed?

I've just tried this myself, and it worked As Expected, although yeah, that docker image is quite a big download - about 680MB.

```
 ltc create xray hatofmonkeys/xray
No port specified, using exposed ports from the image metadata.
	Exposed Ports: 8080
No working directory specified, using working directory from the image metadata...
Working directory is:
/app
Monitoring the app on port 8080...
No start command specified, using start command from the image metadata...
Start command is:
/bin/bash /app/cloudrocker-start-1c4352a23e52040ddb1857d7675fe3cc.sh /app npm start
Creating App: xray
.............................................................................................................08/05 08:36:24.43 [APP|0] Successfully created container
08/05 08:36:25.07 [APP|0] > xray@1.1.0 start /app
08/05 08:36:25.07 [APP|0] > node index.js
08/05 08:36:25.09 [HEALTH|0] healthcheck failed
08/05 08:36:25.10 [HEALTH|0] Exit status 1
.08/05 08:36:25.18 [APP|0] spawned cluster, kill -s SIGUSR2 27 to reload
08/05 08:36:25.62 [HEALTH|0] healthcheck failed
08/05 08:36:25.63 [HEALTH|0] Exit status 1
.08/05 08:36:26.16 [HEALTH|0] healthcheck failed
08/05 08:36:26.17 [HEALTH|0] Exit status 1
08/05 08:36:26.69 [HEALTH|0] healthcheck failed
08/05 08:36:26.70 [HEALTH|0] Exit status 1
.08/05 08:36:27.23 [HEALTH|0] healthcheck failed
08/05 08:36:27.24 [HEALTH|0] Exit status 1
08/05 08:36:27.94 [HEALTH|0] healthcheck failed
08/05 08:36:27.95 [HEALTH|0] Exit status 1
.08/05 08:36:28.48 [HEALTH|0] healthcheck failed
08/05 08:36:28.49 [HEALTH|0] Exit status 1
08/05 08:36:29.01 [HEALTH|0] healthcheck failed
08/05 08:36:29.02 [HEALTH|0] Exit status 1
.08/05 08:36:29.54 [HEALTH|0] healthcheck failed
08/05 08:36:29.54 [HEALTH|0] Exit status 1
.08/05 08:36:30.24 [HEALTH|0] healthcheck failed
08/05 08:36:30.25 [HEALTH|0] Exit status 1
08/05 08:36:30.79 [HEALTH|0] healthcheck failed
08/05 08:36:30.80 [HEALTH|0] Exit status 1
.08/05 08:36:31.33 [HEALTH|0] healthcheck passed
08/05 08:36:31.33 [HEALTH|0] Exit status 0

xray is now running.
App is reachable at:
http://xray.192.168.11.11.xip.io
```

I happen to be tracking the master branch; I could look into trying to replicate using your specific version.

**Comment by teodor-pripoae** [comment]
Hi, I'm using 0.2.7 on both vagrant and cli.

**Comment by teodor-pripoae** [comment]
I have ltc target set up with a custom domain, matching `*.mydomain.com` to `192.168.11.11` if this helps. I also tried to setup app setting `RECEPTOR_URL` to `http://receptor.mydomain.com`, but it didn't work either.

**Comment by menicosia** [comment]
@teodor-pripoae,

I was able to have a similar problem while testing the release candidate for v0.3.0. I was able to get the app to work by giving it more RAM: `ltc create xray hatofmonkeys/xray -m 512`

I suspect it's failing to come up because the default, 128MB, is not sufficient. Can you try this, and see if giving the app more RAM solves your problem? (If it does, please feel free to close the ticket. If it doesn't, let me know and I'll try to get more eyes on it.)

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by teodor-pripoae** [comment]
I tried now using v0.3.0 and it works, both with memory settings and without. So it looks like there is a problem using v0.2.7.

**Comment by menicosia** [comment]
Hi @teodor-pripoae,

Just an update.

Thanks for letting me know about @hatofmonkey's Docker image of xray. I didn't know about it before.

I was disappointed, however, to notice that it's an older version of xray. I wanted the shiny latest version, so I tested Lattice v0.3.0's `build-droplet` functionality on the [xray](https://github.com/pivotal-cf-experimental/xray) repo. Happily, this command works as expected:

> ltc build-droplet xray nodejs -t 4m

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
