### ISSUE TITLE
AWS images do not exist in EU regions (cannot deploy)

### ISSUE THREAD

**Issue by scotttag** [cloudfoundry-incubator/lattice#158]
When attempting to deploy a new deployment in Ireland or Frankfurt I get:
* Error launching source instance: AuthFailure: Not authorized for images: [ami-e3395194]
        status code: 400, request id: []
* Error launching source instance: AuthFailure: Not authorized for images: [ami-e3395194]
        status code: 400, request id: []

It looks like the images specified in variables.tf (ami-e3395194 in eu-west-1, ami-d6cef1cb in eu-central-1) don't actually exist in the AWS marketplace, I presume their visibility has been changed or the images removed?

Unless I'm missing something obvious? (might be...)

**Comment by menicosia** [comment]
Hey @scotttag,

Thanks for bringing this up. We'll look at it ASAP.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by davidwadden** [comment]
@scotttag 

I reviewed all our AMI's configured at https://github.com/cloudfoundry-incubator/lattice/blob/master/terraform/aws/variables.tf#L37-L50

The following were set to Private:

        ap-northeast-1 = "ami-66834c66"
        ap-southeast-1 = "ami-50ffc002"
        ap-southeast-2 = "ami-57136c6d"
        eu-central-1 = "ami-d6cef1cb"
        eu-west-1 = "ami-e3395194"
        sa-east-1 = "ami-8d8d0a90"

I've changed them to Public.  Try again and let us know if it works

**Comment by scotttag** [comment]
Yes this works now, many thanks
