### ISSUE TITLE
Spawn debug container

### ISSUE THREAD

**Issue by teodor-pripoae** [cloudfoundry-incubator/lattice#159]
Hi,

Is there any planned option to spawn a shell in an existing container for debug purposes (similar to docker exec) ? Or is there any option to run a new app with the same image interactively, changing command to `/bin/bash`, `rails console`, etc ?

**Comment by menicosia** [comment]
Hi @teodor-pripoae,

Yes, please see the story [#90425204](https://www.pivotaltracker.com/story/show/90425204) which will leverage Diego's SSH functionality.

You can read more about Diego's SSH in the [mailing list thread](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/GCFOOYRUT5ARBMUHDGINID46KFNORNYM/).

This story will be coming soon after we wrap up the buildpack support work currently under way.

Closing for now, though as always, please feel free to re-open.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
