### ISSUE TITLE
GO build in Windows fails

### ISSUE THREAD

**Issue by git-pradeep** [cloudfoundry-incubator/lattice#163]
Is it possible to build the lattice cli for windows? Below is the output when I try to build

```
$ go install github.com/cloudfoundry-incubator/lattice/ltc
# github.com/cloudfoundry-incubator/lattice/ltc/terminal/password_reader
github.com\cloudfoundry-incubator\lattice\ltc\terminal\password_reader\password_reader_unix.go:25: cannot use 0 (type int) as type syscall.WaitStatus in assignment
github.com\cloudfoundry-incubator\lattice\ltc\terminal\password_reader\password_reader_unix.go:52: undefined: syscall.Wait4
github.com\cloudfoundry-incubator\lattice\ltc\terminal\password_reader\password_reader_unix.go:62: undefined: syscall.ForkExec
github.com\cloudfoundry-incubator\lattice\ltc\terminal\password_reader\password_reader_unix.go:71: undefined: syscall.ForkExec
github.com\cloudfoundry-incubator\lattice\ltc\terminal\password_reader\password_reader_unix.go:73: undefined: syscall.Wait4
```

**Comment by davidwadden** [comment]
@git-pradeep we don't yet support windows for lattice or the `ltc` CLI.   [[#98709542](https://www.pivotaltracker.com/story/show/98709542)] and [[#98709570](https://www.pivotaltracker.com/story/show/98709570)] have been previously created to address the issue you reported.

Please take a look at [[##1932490](https://www.pivotaltracker.com/epic/show/1932490)], our upcoming epic for windows support.   This work is likely still several months out at this point.

**Comment by git-pradeep** [comment]
I'm closing this issue as the support for windows is inherently missing. I'm trying a work around by accessing lattice from the ubuntu vm.

Facing some issue in the work around so I have created a new one  https://github.com/cloudfoundry-incubator/lattice/issues/192
