### ISSUE TITLE
droplet commands require a "Droplet Store" configured by ltc target

### ISSUE THREAD

**Issue by shalako** [cloudfoundry-incubator/lattice#165]
1. droplet store?

https://github.com/cloudfoundry-incubator/lattice/blob/master/docs/ltc.md#building-and-launching-droplets

"The -droplet commands require a "Droplet Store" configured by ltc target."

This implies that something special needs to be done with the `ltc target` command to configure a Droplet Store. How does one do that?

2. 

https://github.com/cloudfoundry-incubator/lattice/blob/master/docs/ltc.md#ltc-build-droplet

`ltc build-droplet DROPLET_NAME http://github.com/buildpack-url`

As aliases are supported, I'd recommend this usage be: 

`ltc build-droplet DROPLET_NAME BUILDPACK`

Document that aliases and url are supported.

**Comment by menicosia** [comment]
Hi @shalako,

Re: droplet store:
The documents may not be 100% straightforward, we transitioned them rather quickly before release, as we ripped out a manually-configured Riak CS instance to an automatically configured WebDAV service. In so doing, we removed the `ltc target-blob` command and revised the documents.

With v0.3.0, if you have Buildpacks support enabled (the default), the droplet store will be automatically configured. The note is suggesting that you can validate that by looking at the output of `ltc target` like this:
```
$ ltc target
Target:		marco@54.210.52.183.xip.io
Blob Store:	marco@54.210.52.183.xip.io:8444
```
I'll add some extra language around the line you've quoted above: https://github.com/cloudfoundry-incubator/lattice/commit/7d2c30608856603bf27175aa3907493cafab02f3

Let me know what you think of that commit; if you think it's good, please feel free to close this issue.

Re: Buildpack target,

I wrestled with that choice as well. I ultimately left the default behavior as using the URL, and the aliases as a convenience. The reason for this is that users can write their own Buildpacks, but they cannot specify aliases. They're mentioned in a line within the `build-droplet` doc at the URL you listed above.

> As an alternative to specifying the URL for a given Buildpack, we also support the following aliases: go, java, python, ruby, nodejs, php, binary, or staticfile.

I'm going to leave it this way for now. If I get a lot of feedback that this is really annoying, I'll gladly change the docs to refer to the aliases by default.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by shalako** [comment]
Your doc commit looks great. That will be very helpful, thank you.
