### ISSUE TITLE
How can I use the Lattice with Nodejs

### ISSUE THREAD

**Issue by agrawalapoorv** [cloudfoundry-incubator/lattice#169]
Hi,

I am trying to run the lattice command inside the nodejs application , but it is not running, can you please me with this.
Is there any NPM package for Lattice.

Regards
Apoorv Agrawal

**Comment by menicosia** [comment]
Hi @agrawalapoorv,

Can you tell us a little bit about what you're trying to accomplish?

One doesn't typically use Lattice from an Node app, rather one can run a node app on Lattice. Something like this (after you've gotten a Lattice up and running via either `vagrant` or `terraform` per the instructions):
```
$ git clone 'https://github.com/pivotal-cf-experimental/xray.git'
$ cd xray
$ ltc build-droplet xray nodejs -t 4m
$ ltc launch-droplet XRAY xray -m 256
```

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by menicosia** [comment]
@agrawalapoorv,

I went back and read your post again, and I realized you were asking something a little different.

No, we don't have an npm distribution of the `ltc` command. Right now, we distribute a static binary, and it can be run anywhere. It's important that you have done an `ltc target` before it can be used for any interaction with a Lattice cluster, however.

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.

**Comment by agrawalapoorv** [comment]
Thanks .
I have one more question , how can I set the environmental variable (Target, username, password) of ltc on system . 
As I am trying to run the ltc create command using a script.

Regards
Apoorv Agrawal

**Comment by menicosia** [comment]
Hi @agrawalapoorv,

I'm sorry, we haven't implemented a non-interactive way to do `ltc target` yet. The story exists, but hasn't been prioritized: [[#98610888](https://www.pivotaltracker.com/story/show/98610888)].

In the meanwhile, I'm afraid `ltc` will reject any non-interactive input (I tried using a here-doc, see story above).

The only suggestion I have is that for `vagrant`-deployed Lattice clusters, the IP address is always static, and there's no user/password challenge. Thus, `ltc target 192.168.11.11.xip.io` should work from a shell script. Unfortunately, this doesn't work for cloud-based deployments, which really should be password protected.

Sorry I can't help more for now. Please feel free to close this issue if we've got your question covered.

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.

**Comment by menicosia** [comment]
Closing due to no response. We're definitely planning to do a non-interactive version of `ltc target`, but I don't have a forecast for when it will be completed.

As always, you are welcome to re-open this issue, or create a new one, if you think that we've missed something. Please help us understand what you are doing, so we can do more to support you in the future.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
