### ISSUE TITLE
Explanation / Overview Missing

### ISSUE THREAD

**Issue by wayneeseguin** [cloudfoundry-incubator/lattice#17]
The README lacks a "about this project / here is what it is / here is why it's great" section at the very top. eg. it jumps directly into using without discussing why you would even want to use it first.

**Comment by jchesterpivotal** [comment]
See also: https://github.com/pivotal-cf-experimental/lattice-app/issues/1

**Comment by wayneeseguin** [comment]
LOL! So it's not just me, ok then! Thanks @jchesterpivotal

**Comment by jbayer** [comment]
you can look at this for now https://docs.google.com/a/pivotal.io/document/d/1WWoQ_d5nR4-P6VfLbAAbzOZIvRj-Xdff2hsjM_ZWRUQ/edit#
