### ISSUE TITLE
php droplet based on cf buildpack fails to launch due to missing apache user

### ISSUE THREAD

**Issue by jistok** [cloudfoundry-incubator/lattice#173]
JMFI:~/working/pivotal/pde> ltc build-droplet pde https://github.com/cloudfoundry/php-buildpack
Submitted build of pde
08/12 18:56:21.32 [BUILD|0] Successfully created container
08/12 18:56:28.72 [BUILD|0] -------> Buildpack version 4.0.0
08/12 18:56:28.80 [BUILD|0] Installing HTTPD
08/12 18:56:35.39 [BUILD|0] Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/httpd/2.4.12/httpd-2.4.12.tar.gz] to [/tmp]
08/12 18:56:35.75 [BUILD|0] Installing PHP
08/12 18:56:35.75 [BUILD|0] PHP 5.5.27
08/12 18:57:45.54 [BUILD|0] Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.5.27/php-5.5.27.tar.gz] to [/tmp]
08/12 18:57:46.86 [BUILD|0] Finished: [2015-08-13 01:57:46.860290]
08/12 18:57:55.88 [BUILD|0] Exit status 0
08/12 18:57:56.47 [BUILD|0] Uploaded /tmp/droplet to http://192.168.11.11.xip.io:8444/blobs/pde/droplet.tgz.
08/12 18:57:56.47 [BUILD|0] Exit status 0
08/12 18:57:56.51 [BUILD|0] Uploaded /tmp/result.json to http://192.168.11.11.xip.io:8444/blobs/pde/result.json.
08/12 18:57:56.51 [BUILD|0] Exit status 0
08/12 18:57:56.56 [BUILD|0] Deleted http://192.168.11.11.xip.io:8444/blobs/pde/bits.zip.
08/12 18:57:56.56 [BUILD|0] Exit status 0
Build completed

JMFI:~/working/pivotal/pde> ltc launch-droplet pde pde
No port specified. Defaulting to 8080.
Creating App: pde
.08/12 18:58:13.44 [APP|0] Successfully created container
....08/12 18:58:17.93 [APP|0] 01:58:17 php-fpm | [13-Aug-2015 01:58:17] ALERT: [pool www] user has not been defined
08/12 18:58:17.93 [APP|0] 01:58:17 php-fpm | [13-Aug-2015 01:58:17] ALERT: [pool www] user has not been defined
08/12 18:58:17.94 [APP|0] 01:58:17 php-fpm | [13-Aug-2015 01:58:17] ERROR: failed to post process the configuration
08/12 18:58:17.94 [APP|0] 01:58:17 php-fpm | [13-Aug-2015 01:58:17] ERROR: failed to post process the configuration
08/12 18:58:17.94 [APP|0] 01:58:17 php-fpm | [13-Aug-2015 01:58:17] ERROR: FPM initialization failed
08/12 18:58:17.94 [APP|0] 01:58:17 php-fpm | [13-Aug-2015 01:58:17] ERROR: FPM initialization failed
08/12 18:58:17.94 [APP|0] 01:58:17 httpd   | [Thu Aug 13 01:58:17.931918 2015] [core:emerg] [pid 27:tid 140257790474048] (22)Invalid argument: AH00024: Couldn't set permissions on the proxy mutex; check User and Group directives
08/12 18:58:17.94 [APP|0] 01:58:17 httpd   | [Thu Aug 13 01:58:17.931974 2015] [proxy:crit] [pid 27:tid 140257790474048] (22)Invalid argument: AH02478: failed to create proxy mutex
08/12 18:58:17.94 [APP|0] 01:58:17 httpd   | AH00016: Configuration Failed
08/12 18:58:18.05 [APP|0] Exit status 78
08/12 18:58:18.12 [APP|0] Creating container
.08/12 18:58:18.77 [APP|0] Successfully created container

**Comment by crawsible** [comment]
Hi @jistok:

Thanks for reporting this to us. This problem seems to affect all apps deployed using PHP buildpack that use the httpd webserver.

As a workaround for the time being, the PHP buildpack can be configured to serve apps with nginx instead, so you might want to try that.

**Comment by jistok** [comment]
Same issue on nginx.

**Comment by damon-pivotal** [comment]
This should be fixed in v0.3.3:

https://github.com/cloudfoundry-incubator/lattice/releases/tag/v0.3.3

**Comment by davidwadden** [comment]
[[#101175234](https://www.pivotaltracker.com/story/show/101175234)] was delivered with [**v0.3.3**](https://github.com/cloudfoundry-incubator/lattice/releases/tag/v0.3.3).

Closing issue.  Open a new one if you're still having issues.

Thanks again for reporting this!
@davidwadden
