### ISSUE TITLE
docs for terraform deploy say that lattice_username has a default but terraform apply fails

### ISSUE THREAD

**Issue by shalako** [cloudfoundry-incubator/lattice#175]
https://github.com/cloudfoundry-incubator/lattice/tree/master/terraform/aws#configure

```
lattice_username: Lattice username (default user)
lattice_password: Lattice password (default pass)
```

This implies that if I don't set these properties, a user will be created for me with username: `user` and password: `pass`. 

Great, so I left the property commented out in `lattice.aws.tf`

```
   # Specify an API username and password for your lattice cluster
    # lattice_username = "<CHANGE-ME>"
    # lattice_password = "<CHANGE-ME>"
```

But then `terraform apply` fails on it.
```
$ terraform apply
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * module root: module lattice-aws: required variable lattice_username not set
```

Upon uncommenting the properties in `lattice.aws.tf` and setting them to the same values as the supposed defaults, the `apply` script gets past this step.

**Comment by menicosia** [comment]
Hi @shalako,

I think you are working off our Develop branch, not a released version, yes?

We have a story in flight ([#100651666](https://www.pivotaltracker.com/story/show/100651666)) to _require_ that the user set credentials. User and password are the one thing that we really want to be custom per deployment vs. providing defaults.

Please close this issue if I guessed your problem correctly!

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
