### ISSUE TITLE
no helpfile for build-droplet

### ISSUE THREAD

**Issue by shalako** [cloudfoundry-incubator/lattice#184]
```
$ ltc build-droplet
Incorrect Usage

$
```

**Comment by davidwadden** [comment]
#198 was submitted to address these concerns.  This fix should land with the [**v0.4.4**](https://github.com/cloudfoundry-incubator/lattice/releases/tag/v0.4.4) release.

Can you try again with our latest nightly build (**v0.4.3-29-g42e5d9e**) and let us know what you think?  

They are available on our [nightly builds](https://lattice.s3.amazonaws.com/nightly/index.html) page.

Thanks,
@davidwadden

**Comment by davidwadden** [comment]
Closing issue - this should land with our next release.  Thanks again!
