### ISSUE TITLE
Getting this error trying to install lattice-app

### ISSUE THREAD

**Issue by omearaj** [cloudfoundry-incubator/lattice#188]
Trying to deploy lattice-app in vagrant version of lattice. I have nothing installed and I'm using the basic memory suggestion of 128 mb of lattice-app. Suggestions?

No port specified, image metadata did not contain exposed ports. Defaulting to 8080.
No working directory specified, using working directory from the image metadata...
Monitoring the app on port 8080...
No start command specified, using start command from the image metadata...
Start command is:
/lattice-app
Creating App: private-lattice-app
.Error, could not place all instances: insufficient resources. Try requesting fewer instances or reducing the requested memory or disk capacity.

Resources look like this for storage:
root@ubuntu-trusty-64:/etc/init# df -h
Filesystem                               Size  Used Avail Use% Mounted on
/dev/mapper/ubuntu--trusty--64--vg-root  8.5G  2.7G  5.4G  34% /
none                                     4.0K     0  4.0K   0% /sys/fs/cgroup
udev                                     2.0G  4.0K  2.0G   1% /dev
tmpfs                                    396M  404K  395M   1% /run
none                                     5.0M     0  5.0M   0% /run/lock
none                                     2.0G     0  2.0G   0% /run/shm
none                                     100M     0  100M   0% /run/user
/dev/sda1                                 65M   37M   24M  61% /boot
vagrant                                  233G   44G  190G  19% /vagrant

**Comment by davidwadden** [comment]
That looks like vagrant, right?  As a habit, we recommend running `ltc test -v` directly after bringing up a new cluster using `vagrant up` or `terraform apply`.  My suspicion is the cluster hadn't warmed up enough when you attempted this command.

**Comment by ihr** [comment]
I get the same error with lattice 0.7 and private docker repository. Running `ltc test -v` produces failed tests.
