### ISSUE TITLE
HTTP proxy inside the building container

### ISSUE THREAD

**Issue by amaltson** [cloudfoundry-incubator/lattice#196]
I'm installed the `vagrant-proxyconf` vagrant plugin and have `$http_proxy` and `$https_proxy` configured correctly in the Vagrant box itself. However, when I try building a droplet, I get:

```
$ ltc build-droplet badges ruby
Uploading application bits...
Uploaded.
Submitted build of badges
09/08 11:52:51.59 [BUILD|0] Creating container
09/08 11:52:51.87 [BUILD|0] Successfully created container
09/08 11:52:52.32 [BUILD|0] Deleted http://192.168.11.11.xip.io:8444/blobs/badges/bits.zip.
09/08 11:52:52.33 [BUILD|0] Exit status 0
09/08 11:52:52.35 [BUILD|0] Exit status 0
09/08 11:52:52.80 [BUILD|0] Failed to clone git repository at https://github.com/cloudfoundry/ruby-buildpack.git
09/08 11:52:52.81 [BUILD|0] Exit status 1
Build failed: Exited with status 1
```

I can't seem to get the logs from the failed task (or don't know how), but I'm pretty sure it's because it couldn't clone the https address and wasn't using the proxy. Is there a way to have the containers Diego spins up to use the proxy? Thanks!

**Comment by menicosia** [comment]
Hi @amaltson,

When running `build-droplet`, you'll need to tell the buildpack about your proxies, something like this: `ltc build-droplet badges ruby -e http_proxy=http://proxy.com -e https_proxy=https://proxy.com`

The Lattice team has an open task to document this, [[#101547386](https://www.pivotaltracker.com/story/show/101547386)] as part of the work done to resolve GH issue #181.

--
Marco Nicosia
Pivotal Software, Inc.

**Comment by amaltson** [comment]
Hey @menicosia 

I had tried that, should have included it in the initial issue creation. I get this:

```
ltc build-droplet badges ruby -e http_proxy=http://proxy:3128 -e https_proxy=http://proxy:3128
Uploading application bits...
Uploaded.
Submitted build of badges
09/08 13:19:40.85 [BUILD|0] Successfully created container
09/08 13:19:41.33 [BUILD|0] Error deleting http://192.168.11.11.xip.io:8444/blobs/badges/bits.zip: 403 Access Denied
09/08 13:19:41.34 [BUILD|0] Exit status 2
Build failed: Exited with status 2
```

**Comment by menicosia** [comment]
Hi @amaltson,

Whoa, that's an interesting error - it looks like your droplet store is not happy.

Two things we can try:
1. How does `ltc test -v` fare?
1. Are you able to see an existing droplet in the droplet store via `ltc list-droplets badges` and if so, are you able to remove it via `ltc remove-droplet badges`?

Finally, it's important for you to use the latest [releases](https://github.com/cloudfoundry-incubator/lattice/releases/) of Lattice, v0.4.0 or v0.3.3. They include a fix so that the buildpacks won't accidentally use your proxy to access the droplet store: [#99515656](https://www.pivotaltracker.com/story/show/99515656)

--
Marco Nicosia
Pivotal Software, Inc.

**Comment by amaltson** [comment]
Hey @menicosia,

I did notice that `ltc test` failed one of the tests on a fresh machine. Here's the output of [ltc test -v](https://gist.github.com/amaltson/6bb93e8aa17ce7a845b0)

I don't see anything in the droplet list:

```
$ ltc build-droplet badges ruby -e http_proxy=http://proxy:3128 -e https_proxy=http://proxy:3128
Uploading application bits...
Uploaded.
Submitted build of badges
09/08 16:39:51.36 [BUILD|0] Creating container
09/08 16:39:51.63 [BUILD|0] Successfully created container
09/08 16:39:52.10 [BUILD|0] Error deleting http://192.168.11.11.xip.io:8444/blobs/badges/bits.zip: 403 Access Denied
09/08 16:39:52.11 [BUILD|0] Exit status 2
Build failed: Exited with status 2
$ ltc list-droplets
Droplet		Created At	Size
$ ltc build-droplet badges ruby -e http_proxy=http://proxy:3128 -e https_proxy=http://proxy:3128
Uploading application bits...
Uploaded.
Error submitting build of badges: build-droplet-badges has already been submitted
```

I'm using Lattice v0.4.0 with the Vagrant box.

**Comment by amaltson** [comment]
I was able to reproduce the same failing test outside of the firewall. However, version 0.4.3 works fine (behind the firewall). I'll double check it works behind the firewall tomorrow.

**Comment by amaltson** [comment]
@menicosia I just start up a new Lattice VirtualBox VM pointing at our HTTP proxy and `ltc test -v` fails. The proxy is set in the VirtualBox setup, but the [droplet test still fails](https://gist.github.com/amaltson/d710e66d5ba6b3060ff5). I can confirm 0.4.3 does work at home though.

**Comment by goonzoid** [comment]
I suspect that having `HTTP_PROXY/HTTPS_PROXY/NO_PROXY` set in `/var/lattice/setup/lattice-environment` isn't enough, as it doesn't pass them through to the `Env` field on Garden's `ContainerSpec` or `ProcessSpec` for the container/process that's doing the `git clone`.

`ltc build-droplet --env HTTP_PROXY=<myproxyaddress>` should be the right command, but that assumes that whatever code is actually doing the `git clone` will honour `HTTP_PROXY` et al.

@menicosia What actually runs inside the container to build the droplet?

**Comment by damon-pivotal** [comment]
@goonzoid @amaltson 

Yes, setting the proxy for vagrant isn't enough. We realize this process is currently confusing and recently updated the README to address this:

https://github.com/cloudfoundry-incubator/lattice#proxy-configuration

We have a story in the backlog to improve this further by adding opt-in automatic proxy detection if you have the http_proxy environment variable set in the terminal where you're running vagrant and ltc.

**Comment by amaltson** [comment]
Unfortunately providing the `env` still doesn't work, same issue as before.

```
ltc build-droplet badges ruby -e http_proxy=http://monty.ms.otpp.net:3128 -e https_proxy=http://monty.ms.otpp.net:3128
Uploading application bits...
Uploaded.
Submitted build of badges
09/18 12:03:32.00 [BUILD|0] Creating container
09/18 12:03:47.73 [BUILD|0] Successfully created container
09/18 12:03:53.26 [BUILD|0] Error deleting http://192.168.11.11.xip.io:8444/blobs/badges/bits.zip: 403 Access Denied
09/18 12:03:53.26 [BUILD|0] Exit status 2
Build failed: Exited with status 2
```

**Comment by damon-pivotal** [comment]
@amaltson

You didn't specify `-e no_proxy` in your example. That's the most important part, to keep the proxy from being used when the containers on the cell communicate with the brain.

**Comment by amaltson** [comment]
@damon-pivotal omg, sorry about that! So stupid of me :-1:. Working now!

**Comment by davidwadden** [comment]
Great!  Going to close this issue - we recently improved the documentation about setting up a cluster proxy [[#103410316](https://www.pivotaltracker.com/story/show/103410316)], too.

We have some upcoming work to improve this experience and allow more flexibility with proxy configurations.  [[##2088022](https://www.pivotaltracker.com/epic/show/2088022)]  Please be on the lookout for those changes (should land around **v0.4.5**) and give us your feedback!

Thanks again!
@davidwadden
