### ISSUE TITLE
Local installation issue: Error verifying target: Invalid Response with status code: 400

### ISSUE THREAD

**Issue by alainsahli** [cloudfoundry-incubator/lattice#207]
Hi

I followed the instructions for setting up lattice locally. `vagrant up` worked fine but then I could not set the target and I always got the following error `Error verifying target: Invalid Response with status code: 400`. I can ping the address and curl requests are also working fine, so I suppose it is not something related with DNS configurations.

I installed it with VirtualBox on a Mac Box with Yosemite.

I could not find a way to get more information about the error (no verbose option?). How can I find out what's the issue?

**Comment by davidwadden** [comment]
hey, you can run `ltc debug-logs` in a separate terminal ..  that's our first recommendation usually

that error message looks like an issue connecting between `ltc` and your cluster though.  can you run this:

`curl -v http://receptor.192.168.11.11.xip.io/v1/desired_lrps`   (assuming your target is `192.168.11.11.xip.io`)

@davidwadden

**Comment by jreypo** [comment]
@davidwadden Got the same error as @alainsahli. When I run `curl` got a 404 error in the response.

After that I tried with lattice v0.4.3 and it worked without issues.

**Comment by alainsahli** [comment]
Hi I tried version v0.5.0 and now it works.

**Comment by davidwadden** [comment]
Thanks @alainsahli  -- closing this issue.
