### ISSUE TITLE
Vagrant VMWare Base Box Does Not Start Successfully

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry-incubator/lattice#26]
The current Vagrant VMWare Base Box (`lattice/ubuntu-trusty-64` `0.1.3`) does not start successfully against VMWare Fusion `7.1.1`.  When starting the VM using `vagrant up` the startup sequence progresses to the point at which the shared folders are enabled and configured, at which point it stalls for quite a long time and eventually fails:

```
$: vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Cloning VMware VM: 'lattice/ubuntu-trusty-64'. This can take some time...
==> default: Checking if box 'lattice/ubuntu-trusty-64' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 192.168.147.135:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Forwarding ports...
    default: -- 22 => 2222
==> default: Configuring network adapters within the VM...
==> default: Waiting for HGFS kernel module to load...
==> default: Enabling and configuring shared folders...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["enableSharedFolders", "/Users/bhale/dev/sources/pivotal-cf-experimental/lattice/.vagrant/machines/default/vmware_fusion/c99920bf-0e3f-4eca-84f0-6484e74b8901/packer-ubuntu-14.04-amd64.vmx", {:notify=>[:stdout, :stderr]}]

Stdout: Error: The VMware Tools are not running in the virtual machine: /Users/bhale/dev/sources/pivotal-cf-experimental/lattice/.vagrant/machines/default/vmware_fusion/c99920bf-0e3f-4eca-84f0-6484e74b8901/packer-ubuntu-14.04-amd64.vmx

Stderr: 
```

Logging into the VM directly and reading the `/var/log/boot.log` seems to indicate that `open-vm-tools` does not start because it [does not detect the `/usr/bin/vmware-checkvm` file in the VM][d].

```
...
* Starting NTP server ntpd                                               [ OK ] 
open-vm-tools: not starting as this is not a VMware VM
* Restoring resolver state                                               [ OK ] 
* Stopping System V runlevel compatibility                               [ OK ] 
```

In attempt to diagnose whether the issue was simply my machine or wider than that, I created a new version of the box locally, with no changes from `master`:

```bash
$ packer build -only=vmware-iso ubuntu-trusty-64.json
$ vagrant box add --name "lattice/ubuntu-trusty-64" packer_vmware-iso_vmware.box
```

With this newly created box (and an update to the `Vagrantfile` to use it), the VM started quickly and successfully.

Can you please build a new version of the VMware base box and update the `Vagrantfile` to use it.

[d]: http://apt-browse.org/browse/ubuntu/trusty/main/amd64/open-vm-tools/2%3A9.4.0-1280544-5ubuntu6/file//etc/init.d/open-vm-tools/

**Comment by onsi** [comment]
Thanks for the sleuthing @nebhale - we'll take a look.  in the meantime, virtualbox should work for you

**Comment by voelzmo** [comment]
Any progress on this one? I also ran into this issue a few days ago. If it is not easy to fix from your side, I'd say just remove the vmware_fusion part, so people don't chase ghosts.

**Comment by onsi** [comment]
@voelzmo @nebhale we're going to remove the vmware_fusion part for now and investigate.

**Comment by davidwadden** [comment]
@voelzmo @nebhale We were able to reproduce your issue with VMWare Fusion 7.1.1 and have published a new vagrant box image (v0.2.0) to Atlas (formerly vagrant cloud).  The change to the Vagrantfile is currently on the develop branch and working its way through the pipeline to get onto master.

**Comment by preillyme** [comment]
I had the same issue but it appears that manually using the (v0.2.0) box works.

**Comment by onsi** [comment]
We think this has been resolved.  Closing it out for now.

**Comment by jandubois** [comment]
FWIW, I still had the same issue with Fusion 7.1.2.  Rebuilding the image locally did fix it.
