### ISSUE TITLE
Don't show password when using `ltc target`

### ISSUE THREAD

**Issue by jtuchscherer** [cloudfoundry-incubator/lattice#30]
Currently, when setting up the ltc cli target, you are prompted for username and password (if required). The password will be echoed back. That's really inconvenient when you want to show lattice in front of a big audience (like I did last night at a meetup).

There are a few strategies on how to hide the password. The CloudFoundry CLI does it here for [Unix](https://github.com/cloudfoundry/cli/blob/fa7bcb07cdb6c6960f0907022bcef83ec4363a47/cf/terminal/ui_unix.go) and here for [Windows](https://github.com/cloudfoundry/cli/blob/fa7bcb07cdb6c6960f0907022bcef83ec4363a47/cf/terminal/ui_windows.go). You could also just use the [Terminal Package](https://godoc.org/golang.org/x/crypto/ssh/terminal) to read the password. But that would mean you have to change your [ConfigCommandFactory](https://github.com/cloudfoundry-incubator/lattice/blob/master/cli/config/command_factory/config_command_factory.go). You would need to get the FileDescriptor for the [input](https://github.com/cloudfoundry-incubator/lattice/blob/master/cli/config/command_factory/config_command_factory.go#L44). (I went down that path in an attempt to create a PR for this issue, but got ratholed - that happens when there is no pairing partner :-( )

**Comment by onsi** [comment]
We have a story for this in the backlog

**Comment by davidwadden** [comment]
https://www.pivotaltracker.com/story/show/88989912

https://github.com/cloudfoundry-incubator/lattice/commit/7f210cf4449d849cf8b49faa1955438116b6fa82
https://github.com/cloudfoundry-incubator/lattice/commit/d9fbc7527a9022939e5fa18b52079da2556a77c6

merged to master with https://github.com/cloudfoundry-incubator/lattice/tree/v0.2.0-7-g9f930ec
