### ISSUE TITLE
lattice should be able to create applications from local docker images

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry-incubator/lattice#35]
Actually, this is a feature request/enhancement:

When calling `ltc create`, I want to specify a docker image I created and exported using `docker export` directly, so I don't need to upload unfinished work to the docker hub.

I don't know if this is already possible, but it seems to me, that handling of rootfs URLs is baked directly into receptor and therefore right now this cannot be done?

Warm regards
Marco

**Comment by cppforlife** [comment]
Was just asking for that for concourse when using fly /cc @vito @onsi

**Comment by onsi** [comment]
@voelzmo - correct, this cannot be done and there are no immediate plans for it.  One approach might be to run a temporary private registry and push your image to that - though I haven't actually tried doing this.

**Comment by georgethebeatle** [comment]
@voelzmo: Me and @hsiliev recently found out that when you sign up with GitHub you get one private repo for free, so maybe you can push your work there? Should be way easier that running the local registry (there is some hassle around securing it with https or allowing insecure registries like crazy).

**Comment by voelzmo** [comment]
Thanks for the replies guys. I'm not going to spin up a private registry, all I wanted to do is trying to get a few apps to run on Diego using lattice. Concerning the private repo at dockerhub: @onsi - I'm not sure if ltc can do logins, haven't tried that yet? I think for now I'll try to use public repos for some things which I can put there.

However, if I am running this on my machine, the need to push the image to some location before being able to `ltc create` seems more complex than it probably should be.

**Comment by onsi** [comment]
`ltc` can't do logins, no - more importantly, the component in Lattice that downloads the docker images (Garden) does not support fetching private images yet.

I agree that the local development experience is somewhat onerous -- optimizing that experience hasn't been in scope for Diego (the runtime that Lattice is built on).  I imagine there may be things that Lattice could do to create a meaningful workflow for a developer, but we haven't invested any effort in that area yet.

**Comment by onsi** [comment]
am gonna close this one out.  we are considering adding a preconfigured private registry to Lattice to make the developer experience more pleasant.
