### ISSUE TITLE
Unable to build ltc from source

### ISSUE THREAD

**Issue by shashidharatd** [cloudfoundry-incubator/lattice#36]
The Readme of ltc says i can build ltc from source using following command:

`go get github.com/cloudfoundry-incubator/lattice/ltc`

but i am getting below errors:

```
root@cf2:~/workspace/lattice/ltc# go get github.com/cloudfoundry-incubator/lattice/ltc
package github.com/docker/docker/autogen/dockerversion
        imports github.com/docker/docker/autogen/dockerversion
        imports github.com/docker/docker/autogen/dockerversion: cannot find package "github.com/docker/docker/autogen/dockerversion" in any of:
        /root/go/src/pkg/github.com/docker/docker/autogen/dockerversion (from $GOROOT)
        /root/gopath/src/github.com/docker/docker/autogen/dockerversion (from $GOPATH)
```

How to resolv this?

**Comment by onsi** [comment]
hi @shashidharatd 

we have updated the instructions on the `develop` branch:
https://github.com/cloudfoundry-incubator/lattice/blob/develop/ltc/README.md

they haven't made it to master yet.

We're using Godeps to vendor our dependencies and the instructions have been updated to use the vendored dependencies.

**Comment by shashidharatd** [comment]
Thank you @onsi for clarification.

**Comment by jhiemer** [comment]
I am not able to get this going. Having the same error as @shashidharatd. 

Go Version: go version go1.4.2 darwin/amd64, and godeps installed. 

Any idea?

**Comment by dhilipkumars** [comment]
@jhiemer in my case i had to resolve the docker autogen manually (things have changed in the docker framework i guess)

```
$cd ltc/Godeps/_workspace/src/github.com/docker/docker
$. ./hack/make/.go-autogen
```
now re-try 'go get' (from the original path) it should work 

ref: http://stackoverflow.com/questions/29170625/missing-package-github-com-docker-docker-autogen-dockerversion

**Comment by shashidharatd** [comment]
hi @jhiemer,
  the readme is updated now. For installing ltc from source follow below instructions.
```
go get -d github.com/cloudfoundry-incubator/lattice/ltc
GOPATH=$GOPATH/src/github.com/cloudfoundry-incubator/lattice/ltc/Godeps/_workspace:$GOPATH go install github.com/cloudfoundry-incubator/lattice/ltc
```
`go get -d github.com/cloudfoundry-incubator/lattice/ltc` will throw up an error, you can safely ignore it. `go get -d` will just download and does not install the specified package. there is no option in `go get` to stop after downloading the package, it will go on and download the package dependencies. that's where we will get the above mentioned error (docker has some auto-generated packages).
Issue the second line which should build the ltc tool. all the package dependencies are vendored in the downloaded ltc path `github.com/cloudfoundry-incubator/lattice/ltc/Godeps`

**Comment by shashidharatd** [comment]
it would have been better if there was a note added about the error when `go get -d github.com/cloudfoundry-incubator/lattice/ltc` is called

**Comment by onsi** [comment]
we'll mention the error in the readme

**Comment by jhiemer** [comment]
thx @onsi and @shashidharatd that worked!
