### ISSUE TITLE
Terraform instructions need clarification

### ISSUE THREAD

**Issue by svrc-pivotal** [cloudfoundry-incubator/lattice#39]
A couple of minor suggestions from a newbie perspective.

Firstly, the Terraform templates require `wget` installed which isn't normally on a Mac unless you've done a `brew install wget`.  The terraform will fail and may require a manual cleanup (`terraform destroy` doesn't consistently clean everything up).

Secondly, in the main Lattice README, for Terraform cluster deployment, suggests "Finally, rename lattice.tf.example to lattice.tf ..." for the various Terraform examples.

If I'm a new Lattice & Terraform user and actually use the `lattice.tf.example` files in the various Github `terraform/aws` or `terraform/google` directories, rather than downloading a seperate example file,  this doesn't work, because Terraform picks up all local `*.tf` files and gets confused, thinking variables in `lattice.tf` aren't set.   For example:
```
worlock:google stuartcharlton$ terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * Required variable not set: gce_client_secrets_file
  * Required variable not set: gce_project
  * Required variable not set: gce_ssh_user
  * Required variable not set: gce_ssh_private_key_file
  * Required variable not set: gce_account_file
```

Whereas if I have `lattice.tf` in an empty directory, `terraform plan` and `terraform apply` work as expected.

**Comment by onsi** [comment]
> Firstly, the Terraform templates require wget installed which isn't normally on a Mac unless you've done a brew install wget. 

We can add a note to `brew install wget` if you don't have it.

> The terraform will fail and may require a manual cleanup (terraform destroy doesn't consistently clean everything up).

This is a race/bug in Terraform.  We have a story further down to look into what we can do to improve things on our end.

> If I'm a new Lattice & Terraform user and actually use the lattice.tf.example files in the various Github terraform/aws or terraform/google directories, rather than downloading a seperate example file, this doesn't work, because Terraform picks up all local *.tf files and gets confused, thinking variables in lattice.tf aren't set.

We're going to switch to e.g. `lattice.gce.tf` - see #43

**Comment by svrc-pivotal** [comment]
Thanks @onsi , re: #43 the main thing I'd suggest is that there should be a note in the docs that the .tf file  for your cloud of choice should be the only .tf file in a directory.

**Comment by davidwadden** [comment]
we changed around the terraform directory structure to put the example .tf file in a separate folder from the other .tf files.  this should be more clear now and you won't run into that issue again.

https://github.com/cloudfoundry-incubator/lattice/commit/de342bd07b37a2a9aa91328a3823182a184dc064

#39 #43 #45 should all be addressed with this change
