### ISSUE TITLE
GCE doesn't require client secret file anymore

### ISSUE THREAD

**Issue by svrc-pivotal** [cloudfoundry-incubator/lattice#40]
The Terraform Google provider only requires an Account JSON file now as of early January; setup was a bit confusing with both required at first.

**Comment by onsi** [comment]
Thanks! Will schedule the work to take a look at this and pull it in.

**Comment by davidwadden** [comment]
Merged manually into develop branch instead

This change required upgrading to Terraform v0.3.7 to support.

https://github.com/cloudfoundry-incubator/lattice/commit/6e2d6cb9349201f7f2356f8bb2d254ff27fc4cfb
