### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by dhilipkumars** [cloudfoundry-incubator/lattice#42]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with lattice. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable lattice on @Sourcegraph by going to https://sourcegraph.com/github.com/cloudfoundry-incubator/lattice and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by onsi** [comment]
We can do this - though the lattice repository is mostly about packaging and the cli - the actual code lives in several other repositories.

**Comment by dhilipkumars** [comment]
Thanks @onsi .  Currently looking at ltc, that should help me get started with it.  Enabling dependent repos will be super brilliant actually.

**Comment by davidwadden** [comment]
@dhilipkumars this should be done.  take a look and let us know
