### ISSUE TITLE
terraform download filename suggestions

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/lattice#43]
Currently all the terraform download links have the same `lattice.tf.example` name; and it ends with `.example` which means my laptop doesn't know what type of file it is (compared to ending with `.tf`).

Proposal for filenames in the release notes:

![image](https://cloud.githubusercontent.com/assets/108/6733116/49de4e90-ce0d-11e4-9a0d-685eb55b4fae.png)

**Comment by onsi** [comment]
+1 - will prioritize this story.

**Comment by davidwadden** [comment]
we changed around the terraform directory structure to put the example .tf file in a separate folder from the other .tf files.  this should be more clear now and you won't run into that issue again.

https://github.com/cloudfoundry-incubator/lattice/commit/de342bd07b37a2a9aa91328a3823182a184dc064

#39 #43 #45 should all be addressed with this change
