### ISSUE TITLE
Concourse setup for the pipeline?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/lattice#44]
I'm trying to learn more about http://concourse.ci - I can see the lattice-pipeline folder in this repo - how do you configure concourse to run these pipeline scripts, pass assets between stages, etc?

/cc @vito

**Comment by onsi** [comment]
Lattice is currently on GoCD so this isn't a great place to look.

@vito are there any publicly visible concourse configs?  Diego's is closed source because it has all sorts of credentials in it.
