### ISSUE TITLE
Terraform for DO configuration issues

### ISSUE THREAD

**Issue by chipchilders** [cloudfoundry-incubator/lattice#45]
When I edit the example lattice.tf file (renamed from lattice.tf.example) to include the required variable values, terraform doesn't believe that the vars are set.

Ex:

```
# terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * Required variable not set: do_token
  * Required variable not set: do_ssh_public_key_fingerprint
  * Required variable not set: do_ssh_private_key_file
```

If I include the variables in the terraform command, it works correctly:

```
terraform plan \
-var 'do_token=mytokenval' \
-var 'do_ssh_public_key_fingerprint=fingerprintval' \
-var 'do_ssh_private_key_file=filelocation'
```

**Comment by davidwadden** [comment]
I think this is a side effect of having the lattice.tf in the same folder as the other .tf files - (e.g., outputs.tf, resources.tf, etc.)  .. try moving the config file to its own folder, then to do the `terraform get -update` and `terraform apply` and see if that works.

this has been reported a couple times - #39 #43 and we're working on clarifying the instructions

**Comment by davidwadden** [comment]
we changed around the terraform directory structure to put the example .tf file in a separate folder from the other .tf files.  this should be more clear now and you won't run into that issue again.

https://github.com/cloudfoundry-incubator/lattice/commit/de342bd07b37a2a9aa91328a3823182a184dc064

#39 #43 #45 should all be addressed with this change
