### ISSUE TITLE
Error when starting app on VMware provider

### ISSUE THREAD

**Issue by camelpunch** [cloudfoundry-incubator/lattice#47]
`Error Starting App: json: cannot unmarshal array into Go value of type receptor.RoutingInfo`

Saw this with the [latest master](https://github.com/cloudfoundry-incubator/lattice/commit/b4c98a622c4ac02d51b20ef63ce7119ccb3ae63c) and v0.2.0

This happened with `ltc start lattice-app cloudfoundry/lattice-app` as well as starting my own image.

I'll keep you posted if I find anything useful!

**Comment by davidwadden** [comment]
@camelpunch  can you give us the output from `ltc -v`  -- i think you might be running an old version of the ltc binary.

the latest release download links are available on:
https://github.com/cloudfoundry-incubator/lattice/tree/master/ltc

or you can get the latest unstable version at:
https://lattice.s3.amazonaws.com/unstable/latest/darwin-amd64/ltc

**Comment by camelpunch** [comment]
Yeah, that looks bad.

```
~$ ltc -v
ltc version 0.0.0
```

**Comment by davidwadden** [comment]
Ok.  going to close this one for now then.  Reopen this issue if that's not the problem
