### ISSUE TITLE
Containers built from scratch image fail

### ISSUE THREAD

**Issue by clintonskitson** [cloudfoundry-incubator/lattice#50]
I am trying to leverage containers that were built from the scratch image to run Go applications that are statically compiled.

ltc create go1billion clintonskitson/go1billion
Start command is:
/bin/go1billion
Creating App: go1billion
..25 Mar 11:29 [APP|0] Failed to create container

If I rebuild the container using "FROM busybox:ubuntu-14.04" (clintonskitson/go1billion2) similar to the lattice-app example, it works.

What Lattice/Diego requirements are there inside of the container that are causing the start of the container to fail?

**Comment by onsi** [comment]
hi @clintonskitson,

We have a short term goal to get Garden (our containerizer) to work with empty containers.  Once that works lands your scratch image should work.  Until then Garden needs `sh` in the container (at least) though are probably other dependencies.  We're going to start characterizing them and removing them soon.

**Comment by clintonskitson** [comment]
Thanks for the quick response!

**Comment by menicosia** [comment]
Hi @clintonskitson,

This story was hanging out in Lattice's queue, so while cleaning up, I just wanted to note that the Garden story @onsi referred to has been finished and released. The story was here: [89107704](https://www.pivotaltracker.com/story/show/89107704), committed in April, and should be in recent versions of Lattice (v0.2.4). I'm leaving this issue closed, please feel free to re-open if this isn't working for you.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
