### ISSUE TITLE
Ubuntu Trusty version referenced in ubuntu-trusty-64.json is deprecated

### ISSUE THREAD

**Issue by sonoble** [cloudfoundry-incubator/lattice#54]
The version of Ubuntu coded into the json is ubuntu-14.04-server-amd64.iso which has been removed and replaced with http://releases.ubuntu.com/trusty/ubuntu-14.04.2-server-amd64.iso.

wget http://releases.ubuntu.com/trusty/ubuntu-14.04-server-amd64.iso
--2015-03-29 18:57:45--  http://releases.ubuntu.com/trusty/ubuntu-14.04-server-amd64.iso
Resolving releases.ubuntu.com (releases.ubuntu.com)... 91.189.88.148, 2001:7b8:3:37:213:136:29:219
Connecting to releases.ubuntu.com (releases.ubuntu.com)|91.189.88.148|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-03-29 18:57:47 ERROR 404: Not Found.

I have updated the .json file and confirmed that I am able to build an image using packer on Ubuntu 14.0.4.  Using the following command:

packer build ubuntu-trusty-64.json

Added it to the vagrant box list:

vagrant box add lattice/ubuntu-trusty-64 ubuntu-trusty-64.box 
Downloading box from URL: file:/home/snoble/lattice/ubuntu-trusty-64.box
Extracting box...te: 1074M/s, Estimated time remaining: --:--:--)
Successfully added box 'lattice/ubuntu-trusty-64' with provider 'virtualbox'!

And after modifying the Vagrantfile vagrant up the image:

root@virtualbox:/home/snoble/lattice# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'lattice/ubuntu-trusty-64'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...

**Comment by menicosia** [comment]
Hi @sonoble,

Thank you much for this Pull Request. A story has been created in our internal tracking system. I have prioritized it for the team, but since there's some extra work in creating a new image, it's not something we can get to immediately. You can follow our progress there, if you like: https://www.pivotaltracker.com/story/show/91363618

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by menicosia** [comment]
Hi @sonoble,

We've released Version 0.2.5 of Lattice, which has switched the base images to Ubuntu Trusty 64 14.04.2. I've been keeping this issue open until that release.

https://github.com/cloudfoundry-incubator/lattice/releases/tag/v0.2.5

Closing this issue, but please feel free to reopen if the release does not sufficiently address this issue.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
