### ISSUE TITLE
Option request: custom healthcheck URL

### ISSUE THREAD

**Issue by bsideup** [cloudfoundry-incubator/lattice#57]
We're using Spring Boot, so "/" healthcheck is useless, we need some kind of "--healthcheck-url=/health" option

**Comment by onsi** [comment]
@bsideup 

Current healthcheck simply monitors a *port* (i.e. ensures that connections to the port can be established) it doesn't hit a URL.  This mirrors the existing cloud foundry behavior.

`ltc` sets this health check up when it submits the application to Lattice.  However, from an API perspective, the health check is completely generic.  It can be any process that returns a happy exit code (0) when the application is healthy and an unhappy exit code when the application is unhealthy.

Surfacing this genericity in `ltc` is not an immediate priority (though we're open to input on priorities!).  The next release will allow you to craft and submit custom [LRP](https://github.com/cloudfoundry-incubator/receptor/blob/master/doc/lrps.md) JSON to the underlying Diego API.  If your docker-image has curl you could easily run `curl` as the health check.

**Comment by onsi** [comment]
Added story in tracker: https://www.pivotaltracker.com/story/show/91461922

**Comment by davidwadden** [comment]
This feature landed on master with **v0.2.4-149-g4687cd7** build and will be included in the **v0.2.5** release.

The above story got repurposed into something slightly different, where lattice uses a healthcheck provided by the docker image itself;  supporting HTTP healthchecks was done with [#92064340](https://www.pivotaltracker.com/story/show/92064340) and the monitoring flags were renamed with [#95161820](https://www.pivotaltracker.com/story/show/95161820). 

Related changes:  
* https://github.com/cloudfoundry-incubator/lattice/commit/b889dc6e208b65ed2c35f447377ee5f5723f0fe5 https://github.com/cloudfoundry-incubator/lattice/commit/66fe7a312ad7e35f418381f30c4945057351afdd
* cloudfoundry-incubator/buildpack_app_lifecycle#8
* cloudfoundry-incubator/docker_app_lifecycle#3

Try it out and let us know!

**Comment by menicosia** [comment]
Hi @bsideup,

We've released Version 0.2.5 of Lattice, which includes the monitor-by-URL feature. I've been keeping this issue open until that release.

https://github.com/cloudfoundry-incubator/lattice/releases/tag/v0.2.5

Closing this issue, but please feel free to reopen if the release does not sufficiently address this issue.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
