### ISSUE TITLE
Private docker registry support

### ISSUE THREAD

**Issue by bsideup** [cloudfoundry-incubator/lattice#58]
Currently it's impossible to create app from private image without custom steps to configure docker itself

**Comment by davidwadden** [comment]
Please see my other post on how this can be configured.  Yes, there are a number of manual steps for now.

https://github.com/cloudfoundry-incubator/lattice/issues/51

**Comment by davidwadden** [comment]
https://github.com/cloudfoundry-incubator/lattice/commit/36d868afaea22cb6c7c43113b101c8aeecd00a4d was made to allow `ltc` to create an app from a private registry (assuming the other directions on #51 to whitelist the private registry are followed).  

This was included in the [v0.2.3](https://github.com/cloudfoundry-incubator/lattice/releases/tag/v0.2.3) release.  Closing this issue.
