### ISSUE TITLE
Option request: "--force" on rm

### ISSUE THREAD

**Issue by bsideup** [cloudfoundry-incubator/lattice#59]
Sometimes lattice is failed to remove app, and there are no options to make sure that removal will be performed 100% sure

**Comment by dhilipkumars** [comment]
yes +1 from me to for this feature.  

plus i also would love. 

```
$ltc rm app1 app2 app2 etc.,
```

or even better with regex.

```
$ltc rm app\*testing
```

**Comment by onsi** [comment]
We're going to update the error message that `ltc` displays.  The request to remove is asynchronous and `ltc` is probably timing out waiting for the remove to complete.

Removes typically resolve very quickly however we have seen some edge cases that we plan on fixing soon.

**Comment by onsi** [comment]
Closing this out as there is no notion of `--force`ing  a remove.
