### ISSUE TITLE
Option request: "--refresh=1s" in "status"

### ISSUE THREAD

**Issue by bsideup** [cloudfoundry-incubator/lattice#60]
Would be awesome to have some kind of continuous "monitoring" command for app status, similar to vz's "--refresh"

**Comment by onsi** [comment]
Sounds like a good idea to me :)

We've added a story:
https://www.pivotaltracker.com/story/show/91375660

It's a lower priority at the moment but we'll get to it eventually.

**Comment by davidwadden** [comment]
This landed on master with v0.2.2-8-g67f60a0g.  Closing this issue.

Let us know if you have any issues with it @bsideup 

https://github.com/cloudfoundry-incubator/lattice/commit/484f1d92f9b6433de2f847dfac7d31443aa3f8ee
