### ISSUE TITLE
Feature request: create app from FS

### ISSUE THREAD

**Issue by bsideup** [cloudfoundry-incubator/lattice#61]
In local development environment it's difficult to create apps from local source, i.e. I have a local project and I want to run it in Lattice. Instead of building an image and pushing it to registry I want to do something like that:
```
$ ls -l
Dockerfile
app.jar
$ ltc create app --from-fs .
```
Which will build an image from local file system.

Otherwise, you can just run repository inside lattice and then do something like:
```
$ docker build -t "1.2.3.4.xip.io/corp/sample-app" .
$ docker push 1.2.3.4.xip.io/corp/sample-app
$ ltc create app 1.2.3.4.xip.io/corp/sample-app
```

**Comment by onsi** [comment]
Lattice consumes and runs Docker images.  Not Dockerfiles.  To make the developer experience a bit more friendly we are considering running a private registry & docker daemon within Lattice to support your second workflow.  We would still defer to the `docker` CLI to build and push the images so developers will be required to install Docker.

**Comment by bsideup** [comment]
@onsi as I said - private registry is totally ok to me and looks like a good solution not only for development, but for test, staging and even production environments. 

Thanks!

**Comment by menicosia** [comment]
Hey @bsideup,

Have you checked out our latest release, [v0.3.0](https://github.com/cloudfoundry-incubator/lattice/releases/tag/v0.3.0)? In this release, Lattice now has Cloud Foundry Buildpack support, and stores the resultant 'droplet' on an internal blob store.

I think this more than addresses your suggestion. I hope you like what we've done. I know you were thinking in the context of Docker images, but we are planning to support extracting a Docker image from the 'droplet' even if they're not required to run on Lattice: [#101094710](https://www.pivotaltracker.com/story/show/101094710). Lattice does not actually use Docker/dockerd to run our containers. Instead it takes a Docker image (and now a droplet) and submits it to Garden, which is our container execution component.

I'm going to close this ticket for now. Of course, if you think we've missed something, please feel free to re-open this issue or create a new one.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
