### ISSUE TITLE
Unsupported docker image

### ISSUE THREAD

**Issue by bsideup** [cloudfoundry-incubator/lattice#62]
Lattice can't start simple container with Docker Registry:

```
$ ltc create -r --routes=5000:registry registry registry
No port specified, using exposed ports from the image metadata.
	Exposed Ports: 5000
No working directory specified, using working directory from the image metadata...
Monitoring the app on port 5000...
No start command specified, using start command from the image metadata...
Start command is:
docker-registry
Creating App: registry
........................................30 Mar 11:00 [APP|0] Failed to create container
30 Mar 11:00 [APP|0] Creating container
....................
registry took too long to start.
http://registry.192.168.11.11.xip.io
```

**Comment by davidwadden** [comment]
The first time attempting to deploy a docker image may time out.  Check `ltc list` after attempting to start to see if the number of instances is "1/1" after a little bit.  The cluster continues to try to start the app even after the `ltc create` command times out.  We've been able to successfully start the registry image by using the --run-as-root argument:

```
11:19 $ ltc logs registry
30 Mar 11:20 [HEALTH|0] healthcheck passed
30 Mar 11:20 [HEALTH|0] Exit status 0
30 Mar 11:20 [RTR|0] registry.192.168.11.11.xip.io - [30/03/2015:16:20:10 +0000] "GET / HTTP/1.1" 200 28 "-" "curl/7.30.0" 192.168.11.1:63030 x_forwarded_for:"192.168.11.1" vcap_request_id:105a7ec9-9eeb-4c06-5f0e-a3a4c37fce56 response_time:0.001975515 app_id:registry

30 Mar 11:20 [APP|0] 192.168.11.11 - - [30/Mar/2015:16:20:10 +0000] "GET / HTTP/1.1" 200 28 "-" "curl/7.30.0"
30 Mar 11:20 [HEALTH|0] healthcheck passed
30 Mar 11:20 [HEALTH|0] Exit status 0
```

when we run:
```
10:49 $ curl http://registry.192.168.11.11.xip.io/
"\"docker-registry server\""
```

**Comment by davidwadden** [comment]
Any updates on this @bsideup ?  We have been able to successfully start the docker registry on Lattice by just passing the `--run-as-root` flag.  The first deployment of a given docker image to Lattice may timeout while it downloads layers, but should come up if you run `ltc status registry` for another minute or two.

**Comment by bsideup** [comment]
I think we can close it. I was able to start it after rebuilding whole lattice system from scratch.

**Comment by davidwadden** [comment]
thanks!   closing this issue.
