### ISSUE TITLE
Non-HTTP services

### ISSUE THREAD

**Issue by bsideup** [cloudfoundry-incubator/lattice#67]
I'm trying to run Redis inside lattice with this command:
```
ltc create -r --routes=6379:redis redis redis
```

But redis protocol is broken:
```
$ redis-cli -p 80 -h redis.192.168.11.11.xip.io
redis.192.168.11.11.xip.io:80> ping
Error: Protocol error, got "H" as reply type byte
```

Is it even possible?

**Comment by onsi** [comment]
right now you only get http routing.  you can do `ltc status redis` to get the ip and port of the lattice container and use those instead.

we have plans to bring tcp routing to the platform but that isn't available yet.

**Comment by bsideup** [comment]
@onsi ok, thanks!

**Comment by onsi** [comment]
closing this -- we'll get to tcp routing eventually
