### ISSUE TITLE
Add equivalent of vcap.application.name environment variable

### ISSUE THREAD

**Issue by spencergibb** [cloudfoundry-incubator/lattice#68]
Perhaps `PROCESS_GUID: "lattice-app"`?

Spring Boot and Spring Cloud like to have a name to work with.  Currently in [spring-cloud-lattice](https://github.com/spring-cloud/spring-cloud-lattice), the `spring.application.name` can be different from the `PROCESS_GUID` which can cause confusion.

I'd love to try my hand at a pull request, I just need to be pointed in the right direction.  Is this even the right repo (garden linux)?

```
PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
CF_INSTANCE_IP: "192.168.11.11",
PORT: "8080",
INSTANCE_INDEX: "0",
INSTANCE_GUID: "d67006dd-abbe-4810-514d-c5fef4f52c24",
CA_CERTIFICATES_JAVA_VERSION: "20140324",
USER: "vcap",
LANG: "en_US.UTF-8",
CF_INSTANCE_PORTS: "61010:8080",
CF_INSTANCE_ADDR: "192.168.11.11:61010",
JAVA_DEBIAN_VERSION: "8u40-b27-1",
JAVA_VERSION: "8u40",
CF_INSTANCE_PORT: "61010",
HOME: "/home/vcap"
```

**Comment by onsi** [comment]
@spencergibb - a PR would be great.  The best place would probably be in `ltc` itself.  `ltc` creates and submits a `DesiredLRP` to [Diego's Receptor API](https://github.com/cloudfoundry-incubator/receptor/blob/master/doc/README.md).  The `DesiredLRP` includes an `env` section that allows you to specify environment variables -- it should be fairly straightforward to add `PROCESS_GUID` there.

**Comment by spencergibb** [comment]
@onsi cool, thanks for the info.
