### ISSUE TITLE
Failure on initial install to AWS

### ISSUE THREAD

**Issue by silarsis** [cloudfoundry-incubator/lattice#72]
Following the instructions at https://github.com/cloudfoundry-incubator/lattice/tree/v0.2.1#clustered-deployment - I'm at the `lattice apply` stage, and this is the tail end of the output:

```
module.lattice-aws.aws_instance.lattice-coordinator (local-exec): Downloading Lattice Release tar from https://s3-us-west-2.amazonaws.com/lattice/releases/v0.2.1-14-g9bccdc0/lattice.tgz => /usr/local/home/silarsis/git/aws_lattice/.lattice/lattice.tgz
module.lattice-aws.aws_instance.lattice-coordinator (local-exec): Download complete
module.lattice-aws.aws_instance.lattice-coordinator: Provisioning with 'file'...
module.lattice-aws.aws_instance.lattice-coordinator: Provisioning with 'file'...
module.lattice-aws.aws_instance.lattice-coordinator: Provisioning with 'remote-exec'...
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec): Connecting to remote host via SSH...
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec):   Host: 52.64.49.88
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec):   User: ubuntu
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec):   Password: false
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec):   Private key: true
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec): Connected! Executing scripts...
module.lattice-aws.aws_instance.lattice-coordinator: Provisioning with 'remote-exec'...
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec): Connecting to remote host via SSH...
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec):   Host: 52.64.49.88
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec):   User: ubuntu
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec):   Password: false
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec):   Private key: true
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec): Connected! Executing scripts...
module.lattice-aws.aws_instance.lattice-coordinator: Provisioning with 'remote-exec'...
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec): Connecting to remote host via SSH...
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec):   Host: 52.64.49.88
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec):   User: ubuntu
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec):   Password: false
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec):   Private key: true
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec): Connected! Executing scripts...
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec): tar: This does not look like a tar archive

module.lattice-aws.aws_instance.lattice-coordinator (remote-exec): gzip: stdin: not in gzip format
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec): tar: Child returned status 1
module.lattice-aws.aws_instance.lattice-coordinator (remote-exec): tar: Error is not recoverable: exiting now
module.lattice-aws.aws_instance.lattice-coordinator: Creation complete
Error applying plan:

1 error(s) occurred:

* Script exited with non-zero exit status: 2

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by onsi** [comment]
hey @silarsis -- did you try this more than once? It looks like a download flaked out on you.

**Comment by silarsis** [comment]
I deleted the .lattice directory and re-ran the apply, and got the same error.

I also tried to run a `terraform destroy` (after all the above) and got the following:
```
Error creating plan: Resource 'aws_instance.lattice-coordinator' does not have attribute 'public_ip' for variable 'aws_instance.lattice-coordinator.public_ip'
```

**Comment by onsi** [comment]
Yes, sadly `terraform destroy` is somewhat janky.  It doesn't handle dependencies correctly.

Looking carefully at your output  it looks like you're downloading `https://s3-us-west-2.amazonaws.com/lattice/releases/v0.2.1-14-g9bccdc0/lattice.tgz`

which doesn't actually exist.

A few questions:

1. Did you download the `lattice.aws.tf` file from the releases page (it links to this: https://cdn.rawgit.com/cloudfoundry-incubator/lattice/v0.2.1/terraform/aws/example/lattice.aws.tf)?

2. What os are you running on?  We use grep plus some funky regexp to parse the url in the .tf file and pick the correct asset to download.  There might be an issue peculiar to your platform in that codepath.

/cc @davidwadden could this be a regexp issue?

**Comment by onsi** [comment]
BTW When `terraform destroy` fails in this way you'll need to use your AWS console to destroy the VMs (EC2) and the remove the VPC (https://console.aws.amazon.com/vpc/home)

**Comment by silarsis** [comment]
Downloaded the .tf file from the releases page, yes.

Running in a debian-based docker image. That image is a bit reliant on local environment so I can't easily share it, but if it's useful I can throw together a simple clean image to replicate the problem...?

I note, I'm running against ap-southeast-2, in case that makes a difference.

Expected to do manual clean-up after destroy broke, yes ;)

**Comment by silarsis** [comment]
Actually, I may have lied - I used the .tf file from the git repo, not from the release. That may be the problem - sorry, I forgot that I'd done that :( Just re-running now with the adjusted source url...

**Comment by silarsis** [comment]
...and that appears to have worked. Many apologies for the spurious issue - closing now :)
