### ISSUE TITLE
Option Request:  'ltc rm APP1 APP2 APP3'

### ISSUE THREAD

**Issue by dhilipkumars** [cloudfoundry-incubator/lattice#73]
Hi Team,
When we have a lot of apps and we want to remove some at once, then it would be convenient to do that in one command just like most of the unix/linux command work.

```
$App Name        Instances       DiskMB          MemoryMB        Route
ltcapp          1/1             1024            128             ltcapp.192.168.11.11.xip.io, ltcapp-8080.192.168.11.11.xip.io => 8080
ltcapp1         1/1             1024            128             ltcapp1.192.168.11.11.xip.io, ltcapp1-8080.192.168.11.11.xip.io => 8080
ltcapp10        0/1             1024            128             ltcapp10.192.168.11.11.xip.io, ltcapp10-8080.192.168.11.11.xip.io => 8080
ltcapp2         1/1             1024            128             ltcapp2.192.168.11.11.xip.io, ltcapp2-8080.192.168.11.11.xip.io => 8080
ltcapp3         1/1             1024            128             ltcapp3.192.168.11.11.xip.io, ltcapp3-8080.192.168.11.11.xip.io => 8080
ltcapp4         1/1             1024            128             ltcapp4.192.168.11.11.xip.io, ltcapp4-8080.192.168.11.11.xip.io => 8080
ltcapp5         0/1             1024            128             ltcapp5.192.168.11.11.xip.io, ltcapp5-8080.192.168.11.11.xip.io => 8080
ltcapp6         0/1             1024            128             ltcapp6.192.168.11.11.xip.io, ltcapp6-8080.192.168.11.11.xip.io => 8080
ltcapp7         0/1             1024            128             ltcapp7.192.168.11.11.xip.io, ltcapp7-8080.192.168.11.11.xip.io => 8080
ltcapp8         0/1             1024            128             ltcapp8.192.168.11.11.xip.io, ltcapp8-8080.192.168.11.11.xip.io => 8080
ltcapp9         0/1             1024            128             ltcapp9.192.168.11.11.xip.io, ltcapp9-8080.192.168.11.11.xip.io => 8080

```
'rm' command actually works quickly for apps that got downloaded and created properly, but not for apps those failed to and are being tried in the background, the 'ltc rm' command wait and timeout for those cases. 

we could use the 'fire-and-forget' feature from ltc and request for removing a bunch of apps.  

It would be great to see something like.
```
ltc rm ltcapp10 ltcapp5 ltcapp7 
```
Even if the client times out i don't have to worry as i know they are taken care in the background plus i wait only for one timeout period maximum. 

What do you think?

**Comment by onsi** [comment]
This seems reasonable to me.  I'm inclined to make `ltc rm` completely async if we go down this path.  having it hang until the application is truly shut down isn't particularly useful/important anyway.

Any thoughts on that @davidwadden

**Comment by davidwadden** [comment]
i agree with that.  doesn't seem useful to wait for shutdown to me either.   what makes sense for actual syntax to remove multiple apps, in that case @onsi?

```
ltc rm app1 app2 app3   # multiple args (proposed)
ltc rm app* # wildcards (+ multiple args?)
ltc rm --all # flag
```

**Comment by dhilipkumars** [comment]
Thanks very much for considering this feature. It looks interesting,  I can try my luck with a PR if you both don't mind.  :-)

**Comment by davidwadden** [comment]
Go ahead @dhilipkumars -- I'd be happy to consider your PR!  Let us know if you have any questions

**Comment by dhilipkumars** [comment]
Hi 
Apologies for the delay in responding. 
I finished with this task and just about to commit but then i saw.
https://github.com/cloudfoundry-incubator/lattice/commit/51e1e5f395b8d5a61591ad1d8cc06a3388049109

the difference is my implementation will still poll on multiple apps untill ltc times out.   Plus it handles some corner cases. 

```
$ltc remove --timeout=10s app1 app10 app2 app3 app
Error Stopping App: app5 is not started. Please start an app first
Error Stopping App: nothing is not started. Please start an app first
Removing app2 app7 app1 app10 app3 app4 app6 app8 app9

Successfully Removed app1.
Successfully Removed app10..
Successfully Removed app7.
Successfully Removed app2.
Successfully Removed app3.
Successfully Removed app4.
Successfully Removed app6.
Successfully Removed app8.

Successfully Removed app9.
```

would you still like to consider mine?

**Comment by davidwadden** [comment]
I apologize for not letting you know sooner we completed this [**(story)**](https://www.pivotaltracker.com/story/show/91801088) -- we decided that `ltc rm` should no longer poll until the app is actually removed (i.e., fire + forget) which simplified this greatly..  You're welcome to take a look at what we did and see if you can offer any improvements, but we probably don't need the PR you referenced above..

**Comment by dhilipkumars** [comment]
Thanks @davidwadden the code looks simple and elegent for 'fire and forget' functionality.  I'm closing this issue as its already implemented.   Thanks again for the feature.
