### ISSUE TITLE
vagrant up fails when using the fusion provider

### ISSUE THREAD

**Issue by cdavisafc** [cloudfoundry-incubator/lattice#74]
```
± | ✓| → vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Box 'lattice/ubuntu-trusty-64' could not be found. Attempting to find and install...
    default: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    default: Box Version: 0.2.0
==> default: Loading metadata for box 'lattice/ubuntu-trusty-64'
    default: URL: https://vagrantcloud.com/lattice/ubuntu-trusty-64
==> default: Adding box 'lattice/ubuntu-trusty-64' (v0.2.0) for provider: vmware_desktop
    default: Downloading: https://atlas.hashicorp.com/lattice/boxes/ubuntu-trusty-64/versions/0.2.0/providers/vmware_desktop.box
==> default: Successfully added box 'lattice/ubuntu-trusty-64' (v0.2.0) for 'vmware_desktop'!
==> default: Cloning VMware VM: 'lattice/ubuntu-trusty-64'. This can take some time...
==> default: Checking if box 'lattice/ubuntu-trusty-64' is up to date...
==> default: Verifying vmnet devices are healthy...
```

And just hangs there

**Comment by davidwadden** [comment]
@cdavisafc what version of vmware fusion are you using?  we've tested with the latest 7.1.1 i believe, there was an earlier report on #26 of something similar, and we rebuilt the vagrant image to fix that, but aren't sure about backwards-compatibility now

**Comment by cdavisafc** [comment]
Good point - I am still on the latest version of 6.x. Am working on getting a license for 7 and will report back.

**Comment by acrlewis** [comment]
Saw this issue with a fusion/vbox vmnet conflict in the past. did you run it in box first, then switch the fusion?

**Comment by cdavisafc** [comment]
It's possible, I don't remember for certain. How do I fully reset from this? What is left after I do a vagrant destroy that causes this?

**Comment by davidwadden** [comment]
the virtualization provider (i.e., virtualbox or vmware fusion) still has networking interfaces after a `vagrant destroy` that attempting to use a different provider will conflict with.  If you simply did a `vagrant up` on Fusion, you'll need to do `LATTICE_SYSTEM_IP=192.168.22.22 vagrant up --provider=virtualbox` to avoid the networking conflict.  This is mentioned at https://github.com/cloudfoundry-incubator/lattice#networking-conflicts.

We're also updating the docs to indicate the minimum supported version for VMware Fusion is 7.x

**Comment by cdavisafc** [comment]
Yes, I have run into that, and have set the LATTICE_SYSTEM_IP when starting the vagrant box. I don't believe that this has anything to do with the lattice vagrant box not starting with the fusion provider though. I've now got fusion 7 and am looking for the latest version of the fusion plugin for vagrant - or I should say, a license for it. I'll report back as soon as I can.

**Comment by acrlewis** [comment]
sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --stop
sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --start

**Comment by davidwadden** [comment]
that is correct.  it's something to do with vmware tools baked into .box image not working properly with vmware provider i think (being out of sync).

**Comment by cdavisafc** [comment]
fusion 7 works fine for me - and I note that the README was updated today to indicate that requirement. Thx.
