### ISSUE TITLE
Compile fail, cannot find "tee2metron" in diego release

### ISSUE THREAD

**Issue by LaynePeng** [cloudfoundry-incubator/lattice#75]
Failed in complie process. I trace the error to the compile file, line:

```
go install github.com/cloudfoundry-incubator/lattice/tee2metron
```

The error message shows:
```
    can't load package: package github.com/cloudfoundry-incubator/lattice/tee2metron: cannot find package "github.com/cloudfoundry-incubator/lattice/tee2metron" in any of:
        /usr/local/go/src/github.com/cloudfoundry-incubator/lattice/tee2metron (from $GOROOT)
        /workspace/Diego/diego-release/src/github.com/cloudfoundry-incubator/lattice/tee2metron (from $GOPATH)
```

**Comment by onsi** [comment]
Hey @LaynePeng,

How have you set up your environment?  We have instructions for developers looking to work on Lattice:
https://github.com/cloudfoundry-incubator/lattice/blob/master/development-readme.md

It's complicated, unfortunately, but it should resolve the actual underlying issue.

**Comment by onsi** [comment]
Please reopen this if this does not work for you.
