### ISSUE TITLE
Error creating app: Invalid field: stack

### ISSUE THREAD

**Issue by asifhuawei** [cloudfoundry-incubator/lattice#79]
While trying to create a docker app on lattice on a fresh installation I am getting the following error

```
root@ubuntu:~/workspace/lattice# ltc create lattice-app cloudfoundry/lattice-app
No port specified, image metadata did not contain exposed ports. Defaulting to 8080.
No working directory specified, using working directory from the image metadata...
Monitoring the app on port 8080...
No start command specified, using start command from the image metadata...
Start command is:
/lattice-app
Error creating app: Invalid field: stack
```
Have someone faced the same issue, if yes then how to resolve this.
Is this problem related to environment setup??

**Comment by dhilipkumars** [comment]
+1.  Nothing changed in my Virutal Machine.  I started seeing this suddenly in my environment too.  (i rebuilt ltc locally today thats all)

it appears that its coming from receptor code.  Any clue will be create.

**Comment by asifhuawei** [comment]
Sorry, its my mistake, I was using an older release file, when I updated my release file to v0.2.2 it started working fine. Recently receptor has removed stack and included rootfs and since my release was old so instead of rootfs stack was sent to receptor.

**Comment by davidwadden** [comment]
@dhilipkumars @asifhuawei  thanks, yes this was a recent fix we made -- [**commit**](https://github.com/cloudfoundry-incubator/lattice/commit/9f628ee8b4f0fa8375d2b78ec318cf5f14342a52) ; please make sure you've downloaded the latest `ltc` binary  and let us know if you still have problems
