### ISSUE TITLE
Feature Request : ltc visualize

### ISSUE THREAD

**Issue by dhilipkumars** [cloudfoundry-incubator/lattice#91]
Hi Team,

I was using ltc visualize (vz) and found that when the number of instances go beyond my current terminal width then the "......"s gets wrapped to the next line.  Now my screen starts to scroll.  

(unfortunatly i had lost the output snippet)

I was wondering if some light weight  'lattice xray' built into ltc would interest the community.  I had been playing with 'https://github.com/gizak/termui' package today and with very few lines of code i got this. 

![image](https://cloud.githubusercontent.com/assets/10920260/7101336/498dcd5e-e072-11e4-9c1a-b38c496be78b.png)

the progress bar seems to animate as and when the lattice-cell-01 changes.  (retained the original ltc vz color combination :-)) 

What do you think? Has this been already considered and dropped? 

Regards,
Dhilip

**Comment by onsi** [comment]
This is awesome -- had we known of termui we would have likely used it.  A
PR would be sweet if you're up for it! :)

**Comment by dhilipkumars** [comment]
@onsi  Thank. :-) Im working on it, i should be able send the PR by tomorrow or day-after to get your first impression.

**Comment by dhilipkumars** [comment]
HI @onsi 

I had experimented with the horizontal progress bars yesterday but they do not seem to fit our requirement where number of lattice cells itself could change in the run-time.  

I have slightly changed the layout using vertical bars and raised a pull request to get your initial feedback.  Please let me know what you think 

https://github.com/cloudfoundry-incubator/lattice/pull/94


Thanks in Advance,
Dhilip

**Comment by menicosia** [comment]
I believe this issue has been addressed by PR #94, thank you very much! Closing now that v0.2.4 has been released. As always, please feel to re-open if you think something would be lost by closing this ticket.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
