### ISSUE TITLE
lattice for Windows ?

### ISSUE THREAD

**Issue by hantsy** [cloudfoundry-incubator/lattice#93]
Is there a plan to support Windows ?

I have read the latest Spring Guides, but it seems the `lattice` CLI only supports Mac and Linux. When the Windows system will be the first class citizen?

Thanks.

**Comment by hantsy** [comment]
[https://github.com/spring-guides/gs-spring-cloud-and-lattice/issues/2](https://github.com/spring-guides/gs-spring-cloud-and-lattice/issues/2#issuecomment-92890704)

**Comment by hantsy** [comment]
@cf-gitbot  Thanks.

**Comment by menicosia** [comment]
Hi @hantsy,

Some people have attempted at getting Lattice to work (see issue #80 and #81) on Windows, but you're right, it's not officially a supported platform. We have written a story to support windows and are tracking it here: [85921380](https://www.pivotaltracker.com/story/show/85921380). You can follow that ticket in Tracker to monitor how we make progress against it.

We'll continue to iterate on making it easier for Windows folks in the meantime with documentation fixes and hopefully the occasional workaround.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by hantsy** [comment]
@menicosia , Thanks for your response. Hope there is a Getting started guide for Windows as expected.
